### ISSUE TITLE
Add examples with GUI on different OS

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#1]
It is image processing library so people would like to see examples with GUI. Need simple resizing window able to draw an image [gray-scale and/or color] and simple drawings for following systems:
- Windows (Win32 Api is preferable)  
- Linux  
- Android  
- iOS  
- ~~QT framework (OS independent)~~  

Example code must be as easy as possible and at the same time it is good to have an option to build without framework or specific tools (not everyone has QT for example).

Example code should follow structure: load image from drive --> show --> wait for user response --> do something on image --> show image

This is simple structure how gui object (window) could look like:

``` cpp
class GuiWindow
{
public:
    GuiWindow(const std::string & caption) { };
    virtual ~GuiWindow() { };

    virtual void show() = 0;

    virtual void resize( uint32_t width, uint32_t height ) = 0; // resize window
    virtual void draw( const Bitmap_Image::Image & image ) = 0; // draw an image
    virtual void wait(uint32_t timeMs) = 0; // wait for event. If time is not 0 then wait for specified time
                                                                  // otherwise any user response such as mouse click or key press
private:
    std::string _caption;
};
```

**Comment by ethanhs** [comment]
The simplest way to do this would be to create a wrapper around libui/Qt, which covers all the platforms you need, plus allows you to choose between the two. Could you explain what you expect the `wait()` function to do?

**Comment by ihhub** [comment]
I corrected the code above but I repeat explanation here too:
```cpp
    virtual void wait(uint32_t timeMs) = 0; 
```

The function has 1 input argument what is time in milliseconds. If the variable is greater than 0 then window waits for specified time (just a normal timer). Otherwise the window must wait for any user action such as mouse button click or key pressing. If we do not have such function then user cannot see what is happening on screen because processing time of images (usually) is very fast. So user will see some sort of fast slide show.

**Comment by ihhub** [comment]
I have added simple example on QT framework without utilizing the wrapper.
