### ISSUE TITLE
Neon implementation of Sum function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#106]
`Sum()` function is not implemented for NEON (SIMD) yet. Please refer to `image_function_simd.cpp` file.

**Comment by 0x72D0** [comment]
I would like to learn more about simd. I will try this one!

**Comment by ihhub** [comment]
Just don't forget to add a unit test of your newly created function for verification (one line code in `unit_test_image_function.cpp`).

**Comment by ihhub** [comment]
@0x72D0 you could also have a look at another SIMD related issue. I've added them recently.

**Comment by 0x72D0** [comment]
ok thanks for the proposition, but I think I will stay with this issue. I have a raspberry pi 3B at home and the datasheet of the CPU say it has the neon extension set, so I can test the function on my raspberry pi. The only problem is my lack of experience with the arm architecture, so do you have good reference for the neon extension? For some reason every arm reference manual I came across seems outdated...

**Comment by ihhub** [comment]
@0x72D0 you can refer to http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0204j/Bcfjicfj.html (the page could load very slow due to big amount of data).

By the way, please include your new function into performance tests (1 line of code in `performance_test_image_function.cpp`) to see the improvement in speed.

**Comment by 0x72D0** [comment]
ok thanks!
