### ISSUE TITLE
Add compilation for FFT CUDA code

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#109]
Currently this code is not included in any tests. The compilation requires `cufft` library.

**Comment by ihhub** [comment]
Hey, @fullset , would you like to try this?

**Comment by fullset** [comment]
@ihhub I'm on vacation for now. I'm going to take a look at this on the next week.

**Comment by fullset** [comment]
@ihhub, Could you explain a bit more detailed about what is required to do?

**Comment by ihhub** [comment]
We need to add `cufft` library into compilation and add `src/cuda/cuda_fft.cuh`, `src/cuda/cuda_fft.cu`, `src/fft.cpp` and `src/fft.h` files into compilation list for CUDA unit tests.
