### ISSUE TITLE
SIMD implementation of ConvertToRgb() function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#115]
We do not have SIMD (SSE, AVX or NEON) implementation of **ConvertToRgb()** function. For the person who is willing to add such code please take a look into an implementation of the function inside `image_function.cpp` and the structure which is used for SIMD code inside `image_function_simd.cpp`. Please do not forget to add unit test for newly created function(s) inside `unit_test_image_function.cpp` (it's just one line code via macros call).

**Comment by 0x72D0** [comment]
I'm gonna try this one next

**Comment by ihhub** [comment]
Sure!

**Comment by ihhub** [comment]
@0x72D0 how is it going? If you need any help, I'd like to discuss :)

**Comment by 0x72D0** [comment]
oh I didn't got the time to start it yet, I should start it tonight

**Comment by ihhub** [comment]
It would be great to see the implementation soon :)

**Comment by ihhub** [comment]
Hi @ihhub are you going to implement NEON code as well? :)

**Comment by ihhub** [comment]
Hi @0x72D0  are you going to implement NEON code as well? :)

**Comment by 0x72D0** [comment]
yeah sure :). I am not sure how to implement the AVX one since the shuffle is a little bit weird...

**Comment by ihhub** [comment]
Don't worry about AVX as of now. It's better to have something than trying to have everything ;) An idea for AVX would come later.

**Comment by ihhub** [comment]
@0x72D0 did you have a time for NEON implementation? :)

**Comment by 0x72D0** [comment]
not yet, I might have some time for this, this weekend.

**Comment by ihhub** [comment]
Closing this issue as AVX implementation is not obvious and we do not have a proper solution.
