### ISSUE TITLE
SIMD implementation of ProjectionProfile() function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#116]
We do not have SIMD (SSE, AVX or NEON) implementation of **ProjectionProfile()** function. For the person who is willing to add such code please take a look into an implementation of the function inside `src/image_function.cpp` and the structure which is used for SIMD code inside `src/image_function_simd.cpp`. Please do not forget to add unit test for newly created function(s) inside `test/unit_tests/unit_test_image_function.cpp` (it's just one line code via macros call) as well as to add performance tests (`tests/performance_tests/performance_test_image_function.`).

For projection on X axis we need to have similar logic which *Accumulate* function does while for Y axis projection we must have a logic similar to *Sum* function.

**Comment by ihhub** [comment]
Hi, @0x72D0. This issue is very similar to #113 . Would you like to have a look?

**Comment by 0x72D0** [comment]
Yeah it would be a pleasure for me to try this one, but I'm a little bit occupied this week, so maybe I can start it this weekend :)

**Comment by ihhub** [comment]
No rush, take your time. Thanks for willing to work (later) on it!

**Comment by 0x72D0** [comment]
I test the performance for projectionProfile, this is the performance when horizontal is true:

![screenshot_20181110_074156](https://user-images.githubusercontent.com/16087328/48301461-959ed880-e4bc-11e8-8791-6085fd99d0ab.png)

and when horizontal is false:

![screenshot_20181110_073934](https://user-images.githubusercontent.com/16087328/48301463-a2233100-e4bc-11e8-8a6c-33dfbe1022cd.png)

the function_pool performance seems to be better on larger image, but worst on small image.

**Comment by ihhub** [comment]
This is what I expected. Multithreaded version is slower for small images because mutex synchronization takes some time.

**Comment by ihhub** [comment]
@0x72D0 are you going to implement SSE and NEON as well?

**Comment by 0x72D0** [comment]
yeah sure, I think, I'm gonna do sse today, but for MEON it migth take a little bit of time before I completed it...

**Comment by ihhub** [comment]
I was wrong regarding thread pool (function pool). It's slower because at the end of operation it copies all results into one buffer. This is done because you cannot pass a part of std::vector. We need to fix such limitation in future.

**Comment by 0x72D0** [comment]
but if I understand well, this limitation only target the ProjectionProfile and the Accumulate function, so it's not that bad :)

**Comment by ihhub** [comment]
Hi @0x72D0 how is your progress on NEON implementation of this function? Do you need any help in this?

**Comment by 0x72D0** [comment]
I didn't start the NEON implementation yet, I didn't get a lot of time lately. I migth have more time at the end of december.

**Comment by ihhub** [comment]
It's okay, no rush. Take your time :)
