### ISSUE TITLE
SIMD implementation of RgbToBgr() function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#117]
We do not have SIMD (SSE, AVX or NEON) implementation of **RgbToBgr()** function. For the person who is willing to add such code please take a look into an implementation of the function inside `image_function.cpp` and the structure which is used for SIMD code inside `image_function_simd.cpp`. Please do not forget to add unit test for newly created function(s) inside `unit_test_image_function.cpp` (it's just one line code via macros call).

**Comment by ihhub** [comment]
Cool!

**Comment by ihhub** [comment]
We don't have any unit tests for **RgbToBgr** function. I'll think how to make a proper test for it.

**Comment by 0x72D0** [comment]
ok no problem

**Comment by ihhub** [comment]
@0x72D0 now you have privileges as a collaborator to edit issues, assign them, change labels and review pull requests :)

**Comment by 0x72D0** [comment]
ok the SSE function is ready for testing :)

**Comment by ihhub** [comment]
Great! Looking forward for a pull request.

**Comment by ihhub** [comment]
@0x72D0 for AVX I'm proposing a way to use shift operator by 16 bits (**_mm256_sll_epi32**) and then use blend function **_mm256_blendv_epi8**. What do you think?

**Comment by ihhub** [comment]
Ah, it won't work that way :( We need to figure out based on shifts...

**Comment by 0x72D0** [comment]
why `_mm256_blendv_epi8` won't work, if we do _mm256_blendv_epi8(result,result,ctrl)?

**Comment by ihhub** [comment]
First of all you need to have all of your B values on first place. Currently they are on third. You have have values in simd: RGBRGBRGB... (I didn't write all). Now to put all B values on R position we could use 16 bit shift but variables are 32 bit so we have: RGBR GBRG. As you can see first 32 bit integer should be shifted by 16 bits, while second cannot be shifted by such amount (out of range).

**Comment by 0x72D0** [comment]
I still didn't found an algorithm for AVX... I think I will go back to this issue later, maybe I'm gonna find more idea
