### ISSUE TITLE
Bitmap code simplification

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#12]
Current code is bulky and it is not obvious as it should be.

Ideally the code must look like this:

``` cpp
Image image = loadBitmap("someplace.bmp");
```

But there is no guarantee that loaded image is gray-scale. So the code should be at least like this:

``` cpp
TemplateImage<uint8_t> image = loadBitmap("someplace.bmp");
```

But then how to convert to normal BitmapImage standard without branching code?

**Comment by lakshmanaram** [comment]
@ihhub Can you explain this issue a bit further. Is this concerned with renaming the methods and values in an intuitive fashion? or something else... :confused:

**Comment by ihhub** [comment]
@lakshmanaram Current bitmap code is designed to cover all possible situations (any type of image including palette). This is good but at the same time it is bad to use. Please run though [```bitmap_operation```](https://github.com/ihhub/penguinV/tree/master/PenguinV/examples/bitmap_operation) example in **example** folder to have a full picture of problem.

First of all the palette is not compulsory so we can avoid ```Bitmap_Operation::RawImageTemplate``` class utilization. Instead of this we could use ```Template_Image::ImageTemplate``` class.
