### ISSUE TITLE
Add RgbaToRgb and RgbToRgba functions

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#122]
1. Add `RgbaToRgb` function to convert **RGBA** image into **RGB** image, and `RgbToRgba` function to convert **RGB** image into **RGBA**. Default value of alpha channel is 255 (for `uint8_t` images). The code should be resided in `image_function.cpp`.
2. Add required unit tests for above functions inside `unit_test_image_function.cpp`

Relates to #36

**Comment by DavieV** [comment]
I'm working on this one, using the "RgbToBgr" functions as a reference.

**Comment by ihhub** [comment]
Cool.
