### ISSUE TITLE
Makefile which includes children folder's makefiles

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#129]
We have many examples in `examples` folder. Each folder contains one or multiple projects. We need to add a single makefile in `examples` folder which could execution the compilation of every individual makefile in all folders and do **not** stop if one of projects fails to compile. Ideally we need to output the number of compiled projects/examples versus overall projects and list failed projects.

**Comment by theryangeary** [comment]
Does this have to be implemented with a Makefile? It seems like it might be easier to do it as a script that uses the children folder's makefiles.
