### ISSUE TITLE
Edge detection code

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#13]
Need some algorithms for edge detection. Simple ones are first-order detectors, like Canny for example.

**Comment by abhinav2296** [comment]
Assign it to me @ihhub.

**Comment by ihhub** [comment]
What type of edge detection are you proposing to do? And could you describe the way of implementation?

**Comment by abhinav2296** [comment]
I will try to implement sobel and canny edge detection algorithms in C++.
