### ISSUE TITLE
Makefile for CUDA performance tests

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#144]
We do not have makefile for performance tests on CUDA but unit tests have. You could have a look at CUDA unit tests makefile to create a makefile for performance tests.

**Comment by ihhub** [comment]
Hi @fullset would you mind to have a look into this task if you have free time for this and willingness to do such?

**Comment by fullset** [comment]
hello, @ihhub
All right, I'm going to do this.

**Comment by ihhub** [comment]
Thank you very much!
