### ISSUE TITLE
Add CODE_OF_CONDUCT.md to the project

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#157]
The task is to add `CODE_OF_CONDUCT.md` file to the root of project with understandable and useful information for contributors. You could refer to example of other open source project as templates (for example [here](https://github.com/mono/mono/blob/master/code_of_conduct.md). Project maintainer email is `penguinv.library@gmail.com`.

**Comment by coderdecoder01** [comment]
I'll take this one

**Comment by ihhub** [comment]
Sure.
