### ISSUE TITLE
GPU (OpenCL) Support 

### ISSUE THREAD

**Issue by betanumerical** [ihhub/penguinV#16]
Are there any plans to add OpenCL enhancements for operations that are easy to parallelise and would benefit from GPU support (such as gaussian blurs)?.

**Comment by ihhub** [comment]
Hi betanumerical,

OpenCL is goo tool for parallelism. We could use it too because it is cross-platform. But for now it is difficult to implements everything in proper form and structure at the same time. So I would say yes but it is not first priority.
