### ISSUE TITLE
Do not execute performance tests for Travis-CI and AppVeyor

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#165]
We should not execute performance tests for Travis-CI and AppVeyor platforms as it has no sense to do it.

This issue relates to #155

**Comment by thirdknife** [comment]
I have started working on this. Will send a PR.

**Comment by ihhub** [comment]
Sure.

**Comment by yannlabou** [comment]
@thirdknife Still working on it or should I take care of it?

**Comment by thirdknife** [comment]
I am still working on this.

**Comment by ihhub** [comment]
@thirdknife , any progress on it? Do you need any help? We little struggle about this because **Appveyor** doesn't support parallel jobs so we waste a couple of minutes for tests.

**Comment by ihhub** [comment]
@yannlabou you could take this issue as we don't have a response from @thirdknife .

**Comment by yannlabou** [comment]
@thirdknife just pass `-E` to `ctest` as in https://github.com/ihhub/penguinV/blob/cc2a371207c85b50edd9a2be78499563a1d25586/appveyor.yml#L38
