### ISSUE TITLE
Add proper description about python compilation on Windows

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#171]
We have a description how to compile Python code. This description locates in `src/python/README.md` file. Current description is for Unix systems. We need to add to-do steps for Windows users as well.

**Comment by dianarg** [comment]
I tested the readme steps on a Windows system using PowerShell.  The process is not too much different from Linux, except that swig.exe was not in a default location for me.  The other difference was that pydoc was not available standalone; you have to use `python -m pydoc`.

**Comment by ihhub** [comment]
It's true. This issue is made to create a very simple description for users who have no intention to do extra moves at all. Why? Because many users once facing a little issue with installation/compilation turn out from the product. That's why it's very important to have a detailed description guiding people step by step even if it's only slightly different from Linux (for example you have to set environmental variable in Windows).
