### ISSUE TITLE
Python module compilation on Travis-CI

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#172]
We have an option to compile Python module of the library (it is just a small chunk of it but a good one). Instructions and module locate in `src/python` module. We need to add compilation of the module into [Travic-CI](https://travis-ci.org/ihhub/penguinV).

**Comment by yannlabou** [comment]
@ihhub Sure.

**Comment by ihhub** [comment]
AppVeyor ignores .travis.yml file changes so don't be surprised if AppVeyor build won't start. Plus yesterday I made AppVeyor to auto cancel previous builds if new build arrives. It's only for PRs.
