### ISSUE TITLE
Python module compilation on AppVeyor

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#173]
We have an option to compile Python module of the library (it is just a small chunk of it but a good one). Instructions and module locate in `src/python` module. We need to add compilation of the module into [AppVeyor](https://ci.appveyor.com/project/ihhub/penguinv/branch/master).

**Comment by ihhub** [comment]
@yannlabou do you know how difficult to implement this?

**Comment by yannlabou** [comment]
@ihhub I'll take a look at it this weekend.

**Comment by ihhub** [comment]
Sure

**Comment by ihhub** [comment]
I think we should make a separate job in AppVeyor to do not mess with C++ code.

**Comment by ihhub** [comment]
@yannlabou did you have a chance to have a look at this issue?

**Comment by yannlabou** [comment]
Sorry. I forgot. Will do tomorrow.

**Comment by ihhub** [comment]
That's fine. It'd be great to have it!

**Comment by yannlabou** [comment]
@ihhub Yeah. Busy days at work but still I'm working on it. Build still failing otherwise I had created a PR.

**Comment by ihhub** [comment]
We could go this way: if you face non easy problem put the code for PR even if it fails and we try to find a solution together. Few minds are better than one ;)
