### ISSUE TITLE
Merge unit and performance common code

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#178]
We have a lot of identical source code in unit and performance tests which is not good. We need to reduce code duplication ( #69 ).
At least we should add a new files called `test/test_helper.h` and `test/test_helper.cpp`. Such files should include following functions under `namespace Test_Helper`:
```cpp
PenguinV_Image::Image uniformImage( const PenguinV_Image::Image & reference = PenguinV_Image::Image() );
PenguinV_Image::Image uniformImage( uint8_t value, const PenguinV_Image::Image & reference = PenguinV_Image::Image() );
PenguinV_Image::Image uniformRGBImage( const PenguinV_Image::Image & reference = PenguinV_Image::Image() );
PenguinV_Image::Image uniformRGBImage( uint8_t value, const PenguinV_Image::Image & reference = PenguinV_Image::Image() );
PenguinV_Image::Image blackImage( const PenguinV_Image::Image & reference = PenguinV_Image::Image() );
PenguinV_Image::Image whiteImage( const PenguinV_Image::Image & reference = PenguinV_Image::Image() );
PenguinV_Image::Image randomImage();
PenguinV_Image::Image randomImage( const std::vector <uint8_t> & value );
std::vector < PenguinV_Image::Image > uniformImages( uint32_t images, const PenguinV_Image::Image & reference = PenguinV_Image::Image() );
std::vector < PenguinV_Image::Image > uniformImages( const std::vector < uint8_t > & intensityValue, const PenguinV_Image::Image & reference = PenguinV_Image::Image() );
uint32_t runCount();
data randomValue( int maximum )
data randomValue( data minimum, int maximum )
```

**Comment by ihhub** [comment]
@MeKot if you need more info about this issue I'd love to explain ;) I've modified the original description to be more clear.

**Comment by ihhub** [comment]
Hi, @MeKot, how is going?

**Comment by MeKot** [comment]
Hi, @ihhub, I have started on it, but got a little sidetracked in the meantime.. I will get back to it and finish it in the next couple of days if that is ok with you

**Comment by ihhub** [comment]
It's totally fine with me :)

**Comment by ihhub** [comment]
Hello, @MeKot any progress so far? :)

**Comment by MeKot** [comment]
Hi, @ihhub, yes, I've moved all the methods into the separate file and started to replace occurences in tests, but that apparently takes a little longer since the test suite is of reasonable size (to ensure that all duplication is gone). I was slowly making my way through this in my free time... Would you like me to pick up the pace?

**Comment by ihhub** [comment]
That's fine. I'm just hoping that you would finish it soon :)

**Comment by ihhub** [comment]
@MeKot of course it would be great to have the implementation as soon as possible but I am not a person to force you in any way to do it faster. In any case you do it voluntarily which is already a great help! ;)

**Comment by MeKot** [comment]
@ihhub some of the methods with same names have different input types in unit_tests and performance_tests, such as ```` uniformImage```` and `````unifromRGBImage`````, but seem to do the same thing. Do you want me to unite them under the same type signature and refactor the rest of the code? Also, some of the methods have slightly different implementation, such as ```randomValue```, specifically in condition `if( maximum == 0 )` for unit_tests and ``if( maximum <= 0 )`` for performance_tests. I wanted to check with you if you think these should be unified and if so which implementation to choose?

**Comment by ihhub** [comment]
@MeKot let's analyse everything step by step:
1. `uniformImage` and `uniformRGBImage` are almost the same except the fact that in **performance_test_helper.h** we set width and height explicitly. From my perspective we can have all of them in one place even without merging, just for example `uniformImage` function would have 4 specifications (and only one would have a real code while others just refer to it).
2. `if( maximum <= 0 )` is for int while `if( maximum == 0 )` is for uint32_t. Both are correct but I prefer uint32_t implementation.

There are some more changes required in existing function but I'll explain it once you create a pull request. You can create pull request even if some work is not done so we could discuss it to find the best solution ;)

No need to be sorry. A good explanation is always a key to find a proper solution.
