### ISSUE TITLE
Modify unit tests for Bitmap operation

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#179]
Current unit test (in `test/unit_tests/unit_test_bitmap.cpp` file) for Bitmap does not cover all situations. What we need is:
1. Rename `LoadSaveGrayScaleImage` into `WhiteGrayScaleImage`. Change filename from "white.bmp" to "bitmap.bmp". Set `PenguinV_Image::Image original` and `PenguinV_Image::Image loaded`
2. Add a new function called `BlackGrayScaleImage` withe the same functionality but to save/load black image.
3. Add a new function called `RandomRGBImage` which obviously does the same as above but generate random RGB image (please refer to `test/unit_tests/unit_test_helper.cpp`). Use `memcmp` to compare each line of images (refer to `src/image_function.cpp` **IsEqual** function as an example.
4. Instead of macros `ADD_TEST( framework, bitmap_operation::LoadSaveGrayScaleImage );` use a direct call `framework.add(WhiteGrayScaleImage, "load and save white gray-scale image"` to have human readable output of tests.

**Comment by lrm25** [comment]
I'll take this one

**Comment by ihhub** [comment]
Sure.
