### ISSUE TITLE
Implement functions in function pool

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#18]
Some basic functions could be done with multithreading. Some of them are:

``` cpp
Flip
Transpose
```
~~ConvertToGrayScale~~
~~ConvertToRgb~~
~~ExtractChannel~~
~~IsEqual~~
~~GammaCorrection~~
~~Resize~~
~~Accumulate~~

**Comment by yunchih** [comment]
Hi, can I work on these?
I guess most of these functions  can be parallelized with OpenMP?
Or just put the element-wise operations of these functions within a lambda and run them with `std::thread`?
Any suggestion?
Thanks

**Comment by ihhub** [comment]
Please refer to **function_pool.h** and **function_pool.cpp** in **_Library_** folder. I think it would answer your questions.

**Comment by yunchih** [comment]
Ok, thanks.  I think I can start by trying to implement one of them.

**Comment by ihhub** [comment]
Relates to #119 , #120 , #121
