### ISSUE TITLE
Remove generated bitmap file after unit test

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#183]
We have unit test for **Bitmap** in `penguinV/test/unit_tests/unit_test_bitmap.cpp` where we generate (save) a bitmap file and then load it but we did not remove the file (cleanup). It's good to do this.

**Comment by lrm25** [comment]
I can take this one too.  Do you want an error message, or do you want it to just quietly fail if it does?

**Comment by ihhub** [comment]
Quietly delete a file after loading it inside each test. No need an error message as it's just garbage cleaner code.

**Comment by ihhub** [comment]
File deletion function put please inside `unit_test_helper`.

**Comment by lrm25** [comment]
Do you need a separate function?  File deletion without error handling is just "remove(<path>)".  If so, I can add it though.

**Comment by ihhub** [comment]
Sorry, I think you are right. We don't need a separate function as this is just one line function call.
