### ISSUE TITLE
CMake: enable back OpenCL unit tests compilation on Appveyor

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#190]
Recently we committed **CMake** changes for OpenCL unit test compilation on Appveyor and Travis-CI. Unfortunately, Appveyor fails with Exception: Exit code **0xc0000135** (you could have a look [here](https://ci.appveyor.com/project/ihhub/penguinv/builds/19740930). The [hot fix](https://github.com/ihhub/penguinV/pull/170/commits/7b76d851b5d7c3d4a8af8456c01e74b4c2000b32) was to disable OpenCL unit test compilation on Appveyor and do not execute compiled executable.

We need at least enable back compilation of OpenCL but do not run the executable file. Ideally we should copy needed **dll** into a directory where we compile the executable file because exception exit code refer to missing dll.

**Comment by yannlabou** [comment]
Claiming this one :)

**Comment by ihhub** [comment]
Yep :)

**Comment by yannlabou** [comment]
@ihhub  Can you check where OpenCL.lib is located on the Appveyor machine? I can't install CUDA on my Windows machine since my graphics driver are not compatible.

**Comment by yannlabou** [comment]
I got it `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64\OpenCL.lib`

**Comment by ihhub** [comment]
It's not possible to check manually but you could create a small script (***.bat file** for example) which would list all files and directories and run this script to find the exact location of the file in Appveyor.
