### ISSUE TITLE
Include BinaryDilate and BinaryErode functions into unit tests

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#191]
These functions are defined in `src/image_function.h` file. We have unit tests for image functions located at `test/unit_tests/unit_test_image_function.cpp`. The definitions of function pointers already exist within the file:
```cpp
typedef void (*BinaryDilateForm1)( Image & image, uint32_t dilationX, uint32_t dilationY );
typedef void (*BinaryDilateForm2)( Image & image, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t dilationX, uint32_t dilationY );

typedef void (*BinaryErodeForm1)( Image & image, uint32_t erosionX, uint32_t erosionY );
typedef void (*BinaryErodeForm2)( Image & image, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t erosionX, uint32_t erosionY );
```

We need to add test functions. In these functions for `BinaryDilate` we create a white (255) image but put few black (0) pixels on random places, for `BinaryErode` we create a black (0) image and put few white (255) pixels.  The result should be fully white or fully black image.

After declaration of these test functions add needed 2 lines code in `namespace image_function`

**Comment by lrm25** [comment]
I'll take this one.  Also, did you mean that the "inputs" to the test should be fully white or fully black images, or did you mean that you should dilate the white image to the point where it becomes completely black, and the opposite when eroding?

**Comment by ihhub** [comment]
The purpose of dilation is to expand white area of image, while for erode - to expand black area. Images must be binary normalised images meaning that they should contain only 0s and 255s.

For dilate case: you create a totally white image and put at random place for example 1 black pixel. After dilation your image must become fully white. Of course, putting multiple pixels would be better for tests :)

**Comment by lrm25** [comment]
Which namespaces do you want the tests in?  There's "image_function", "function_pool", "avx", "neon", and "sse".

**Comment by lrm25** [comment]
Do you think it would be helpful to have test cases or a single test case for an image that can't be dilated (such as a 1x1 black image, or any fully black image or area)?  What do you think is the best way to add test cases that run only once to this framework?  I'm using a static bool right now to prevent the single same scenario from running 1000 times, but is there a better method?

**Comment by ihhub** [comment]
An image that cannot be dilated is not a bug. If image is totally black or white then nothing you could do despite of image size.

Please, do not use static variables. A loop in 1001 cycles is design to catch all potential problems. You have to generate a random size image for each iteration.

**Comment by lrm25** [comment]
Sorry if I wasn't clear.  I meant a unit test to make sure that things that shouldn't be dilated are NOT dilated.  And I was just concerned that strictly relying on random value generation can miss edge cases that should be checked individually (such as 1x1 images, images with 1 row or column, etc.).

Also, I've got the commit ready, but I noticed the makefile issues.
