### ISSUE TITLE
Add MakeFile files for all example projects

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#20]
Using command line is inconvenient when project contains a lot of file plus end user doesn't like to do extra moves to copy, paste, run and etc.

**Comment by rahul-kumi** [comment]
I will take this up.

**Comment by rahul-kumi** [comment]
Any things that I need to keep in mind before I proceed?

**Comment by syclik** [comment]
@ihhub: I found this issue through the hacktoberfest tag. Can you provide a little more detail and I can see if I can help? 

Specific questions:
- what folder do you want the user to run from? If we took the `bitmap_operation` example, do you want someone to run from `PenguinV/examples/bitmap_operation/` or from `PenginV/examples/`?
- what C++ flags do you want by default? what C++ flags do you envision users would adjust?
- do you want a makefile to include that would help with additional examples?
- do you want every example to be called `application`?

**Comment by ihhub** [comment]
Hi. Of course you can. Before staring please look into pending pull request #21.
Answering for your questions:
- inside folder
- minimum requirements: Wall (to catch all warnings), c++11
- no
