### ISSUE TITLE
Compilation failure doesn't fail Travis-CI job

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#204]
Recently we move logic for `script:` from **.travis** file into `script.travis/run_script.sh`.  This script always returns **0**  (pass) even if compilation (via CMake) fails. Before this change the code for `script:` was:
```bash
  - mkdir build && cd build/
  - cmake ../ && cmake --build . && ctest --extra-verbose
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ../test/unit_tests/cuda; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ..; fi
```
which makes bash to check each line for return code.

We need to find a compromise to run compilation with correct checks and to do not run compilation for static analysis job.

**Comment by yannlabou** [comment]
Will do
