### ISSUE TITLE
SIMD implementation of Hough Transform

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#207]
We have _Hough Transform_ implementation of CPU (`src/math/hough_transform.h`). We want to add SIMD (**NEON**, **AVX** or **SSE**) implementation of the same function. The finest part for SIMD integration is this loop:
```cpp
for ( ; point != pointEnd; ++point, ++distanceVal )
    (*distanceVal) = point->x * sinVal + point->y * cosVal;
```

1. Create new files named `src/math/hough_transform_simd.h` and `src/math/hough_transform_simd.cpp`
2. Put the function under `Image_Function_Simd` namespace
3. Don't forget SIMD detection code which you could find in `src/image_function_simd.h` and `src/image_function_simd.cpp`

**Comment by ihhub** [comment]
Hi, @0x72D0 would you like to work on it?

**Comment by 0x72D0** [comment]
yeah sure

**Comment by 0x72D0** [comment]
@ihhub I have some problem with c++ namespace, I try to use the simd::actualSimdType() in my hough_transform_simd.cpp but for some reason g++ say that actualSimdType is not a member of 'simd' here's the block of line:
```namespace Image_Function_Simd
{
    bool HoughTransform( const std::vector< Point2d > & input, double initialAngle, double angleTolerance, double angleStep, double lineTolerance,
                         std::vector< Point2d > & outOnLine, std::vector< Point2d > & outOffLine )
    {
        return simd::HoughTransform( input, initialAngle, angleTolerance, angleStep, lineTolerance, outOnLine, outOffLine, simd::actualSimdType() );
    }
}
```
do you know the problem? you can see the full code here: https://github.com/0x72D0/penguinV/tree/hough_transform_AVX

**Comment by ihhub** [comment]
`simd::actualSimdType()` is a function which locates in `image_function_simd.cpp` file (lines 1590-1608) meaning that it is unaccessible. You have to define your own in `hough_transform_simd.cpp` file or move the code to some common place/file. I'd recommend to use second way but we should handle it gently.

**Comment by ihhub** [comment]
@0x72D0 I'll make some changes in code to enable a proper support of SIMD across all files. I'll let you know once it's finished.

**Comment by ihhub** [comment]
This issue relates to #216 .

**Comment by ihhub** [comment]
@0x72D0 now you can complete this task with ease :)

**Comment by ihhub** [comment]
Hi, @0x72D0 are you going to complete this task or have a try with Shift function?

**Comment by 0x72D0** [comment]
I think I'm gonna complete this task first now that proper support of SIMD across all files is implemented

**Comment by ihhub** [comment]
@0x72D0 2 things you need to keep in mind:
1. Original code uses `Point2d` structures which are not a normal array. You might need to convert them into 1D array to use for SIMD code
2. We're going to implement `double` and `float` version of this code so SIMD code should do the same.

To make performance tests you need a proper plan for this. I'm proposing to generate 1000 points with incremental X axis by 1 while Y axis value remains 0: [0, 0], [1, 0], [2, 0]... [999, 0]. For Hough transform code set initial angle as 0, angleTolerance - 10 degrees (convert to radians), angleStep - 0.2 degree (convert to radians), lineTolerance - 1 pixel.

**Comment by ihhub** [comment]
A small correction for my first point: use branching code. Check if **Point2d** is a [standard layout](https://en.cppreference.com/w/cpp/types/is_standard_layout). If yes you can directly use SIMD code on it. Otherwise you have to copy data into an array.

**Comment by ihhub** [comment]
Or maybe not :( We would introduce some extra dependencies. Yeah, let's do initial way then. After we could merge everything into one piece of code.

**Comment by 0x72D0** [comment]
ok let's stay with the original plan then :)

**Comment by 0x72D0** [comment]
And to handle the double and float type should I make a template specialization of the two types?

**Comment by ihhub** [comment]
Yes, you should. Ideally, if it's possible could cover #216 issue together with this one?

You could check structure for a standard layout at application startup time as:
```cpp
namespace
{
    const bool simdFloatSupported = std:: is_standard_layout<Point2DBase<float>>::value;
    const bool simdDoubleSupported = std:: is_standard_layout<Point2DBase<double>>::value;
}
```

and then in the code use these variables as needed.

**Comment by 0x72D0** [comment]
ok I will implement #216 first and continue with #207 after finishing the first one, It'll allow me to improve my understanding of the templates :)

**Comment by ihhub** [comment]
Nice! Thanks a lot! If you need any questions regarding that issue please ask :)

**Comment by ihhub** [comment]
@0x72D0 by the way the code has 2 places for SIMD implementation, where we calculate a distance and this code is similar. I'm thinking that we might need to create a function just for this. What do you think?

**Comment by ihhub** [comment]
@0x72D0 create unit tests for `double`. Usually it's slower than `float` :)

**Comment by ihhub** [comment]
For unit tests just put them within the same unit tests file where CPU code locates: `src/test/unit_tests/unit_test_math.cpp`

**Comment by ihhub** [comment]
Closing this issue as we don't have a proper solution to speed up original algorithm via SIMD.
