### ISSUE TITLE
Float specification of Hough Transform function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#216]
We have Hough Transform implementation which locates in `src/math/hough_transform.h` and `src/math/hough_transform.cpp` files. This implementation is based on `double` type usage. We need to have  **float** implementation as well but without duplication of function. The changes we need:
1. In header file use `PointBase2D<double>` instead of `Point2d`
2. Add the same function but all input data is **float** based
3. Rename existing `HoughTransform` function to `runHoughTransform` and move it to unnamed namespace within the file
3. Make newly created `runHoughTransform` function template based function
4. Make `minimumLineTolerance` and `minimumAngleStep` variables as float (no harm in this)
5. Call `runHoughTransform` from `HoughTransform` for **float** and **double** with needed template specification.
6. Modify unit tests (`test/unit_tests/unit_test_hough_transform.cpp`) to have 2 independent unit test function.

**Comment by 0x72D0** [comment]
I made all the seven step, but when I test the function with double it gave me a segfault at the sort function (hough_transform.cpp:58), any idea why? Here's the code: https://github.com/0x72D0/penguinV/blob/houghTransformFloat/src/math/hough_transform.cpp

**Comment by ihhub** [comment]
You made two specifications of the same function while there is no template function. Please take a look at isEqual function in stc/math/math_base.h file:

    template <typename _Type>
    bool isEqual( const _Type & value1, const _Type & value2 )
    {
        return ( value1 == value2 );
    }

_Type would be your variable type: float or double.

**Comment by 0x72D0** [comment]
ok I add the template function, but I still have the same segfault error with the `std::sort` function :(

**Comment by 0x72D0** [comment]
ok, I remove them, but having the same problem... It's weird the only things that change in the double version is `Point2d` -> `PointBase2D<double>` but `Point2d` is a template of `PointBase2D<double>`

**Comment by ihhub** [comment]
Could you please create a pull request for this? Then it would be easy to identify what was changed in original code?
