### ISSUE TITLE
Fix makefile (include missing files) for unit tests

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#225]
[Recently](https://github.com/ihhub/penguinV/commit/d2efec1d70e85210980561b113643613fa2b8778) we added FFT tests to our unit test project. Changes were made for Visual Studio project files and for CMake. We need exact changes for makefile which locates at `test/unit_tests/makefile`

**Comment by lrm25** [comment]
I took care of this.  The fix is in the pull request for the binarydilate/binaryerode issue.
