### ISSUE TITLE
Travis-CI: static analyser still shows invalid lines

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#226]
[Recent commit](https://github.com/ihhub/penguinV/commit/d4b94aaf942ed1840e052abf3608eab76a81df72) was supposed to hide output lines which contain specific word pattern. Unfortunately, this code just remove that word pattern instead of not showing lines.

In adding to this we have hide lines which contain ` not found in expected header ` word pattern.

**Comment by ihhub** [comment]
@yannlabou I think you would be interested in this :)

**Comment by ihhub** [comment]
How about this solution (which is not optimal but at least you could get an idea):
`cppclean src test examples | grep -v " not found in expected header " | grep -v " does not need to be #included; use a forward declaration instead" | grep -v " not found in any directly #included header"`

I tested on my side and it works fine.

**Comment by yannlabou** [comment]
Fixing it in /pull/230
