### ISSUE TITLE
Add dynamic code analyser as a separate Travis-CI build job

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#227]
We're facing a random segmentation fault issue on Windows builds (#224 ). To find it and to prevent future potential issues we could create a separate Travis-CI build job with debug build on **Linux**. We could use **[valgrind](http://valgrind.org/)** as an analyser and see how it goes. As of now we don't need to install CUDA for such build job.
We should pass the build in any case as it could produce a lot of output code.

**Comment by yannlabou** [comment]
Will do :)
