### ISSUE TITLE
Add one command line argument for unit and performance tests

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#234]
Recently [we've added](https://github.com/ihhub/penguinV/commit/99d0e3514cd001c91f588f239e1113fb5f8ff6d9) command line argument for unit tests (`test/unit_tests/unit_tests.cpp`) application which is an integer for setting iteration count for each tests. We need to do the same for the following files:
```bash
test/unit_tests/cuda/unit_tests_cuda.cpp
test/unit_tests/opencl/unit_tests_opencl.cpp
test/performance_tests/performance_tests.cpp
test/performance_tests/cuda/performance_tests_cuda.cpp
```

Please add exactly the same function in `test/performance_tests/performance_tests_helper.cpp` as it'd one for `test/unit_tests/unit_tests_helper.cpp`.

**Comment by ihhub** [comment]
@MeKot would you like to work on this issue? It is related to work which you done in last pull request.

What we need is to move
```cpp
    uint32_t runCount(); // fixed value for all test loops
    void setRunCount( uint32_t count );
```
from **test/unit_tests/unit_test_helper.h** and **test/unit_tests/unit_test_helper.cpp** into **test/test_helper.h** and **test/test_helper.cpp**. Then modify `setRunCount` function to accept 3 arguments such as `int argc, char * argv[], uint32_t count`, where **count** is a default value which is set now separately for unit and performance tests.
Inside the function you put such logic:
```cpp
void setRunCount( int argc, char * argv[], uint32_t count )
{
    testRunCount = count;
    if ( argc >= 2 ) {
        const int testCount = std::atoi( argv[1] );
        if ( testCount > 0 )
            testRunCount = static_cast<uint32_t>( testCount );
    }
}
```
So you can call this function from **main** directly without extra code.

**Comment by MeKot** [comment]
@ihhub Yes, absolutely! It looks like it should be quite quick to do!
