### ISSUE TITLE
Fix compilation warnings in kissfft (C language) code

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#237]
We use **kissfft** C library for FFT computations on CPU, which locates at `src/thirdparty/kissfft`. Unfortunately compiler on Linux and MacOS complains about multiple warnings during the compilation. These warnings you could find in [Travis-CI build](https://travis-ci.org/ihhub/penguinV) under ` CUDA=8.0.61-1 CMAKE_OPTIONS="-DPENGUINV_BUILD_TEST=ON"` job for example. Ideally we need to fix all of them to to do mess compilation log and as everybody know warnings are potential errors in the code.

**Comment by fullset** [comment]
Hi, @ihhub 
Should we care about kissfft future possible updates in the original repository? If we add a lot of changes to reduce warnings this copy will be different from the original.

**Comment by ihhub** [comment]
**kissfft** library is pretty stable at the moment and there are no major changes in repository. From another side there are changes after all but then we need to solve a problem of compilation of our project on Windows. So we have 2 sides problem at the moment.

We need to think about this wisely.
