### ISSUE TITLE
Set iteration count for unit tests on AppVeyor to 500 via command line argument

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#241]
**AppVeyor** doesn't support parallel job execution. In this case full build takes around 30 minutes which is in about 2 times slower than a build on Travis-CI. To reduce this timing we could set an iteration count for unit tests compiled application. Default value for iterations is 1001. We need to set the value to **500**.

**Comment by yannlabou** [comment]
@ihhub Must it be a command line argument? The simplest solution looks like 
```
if(CMAKE_HOST_WIN32)
    add_test(NAME unit_test COMMAND unit_tests 500)
else()
    add_test(NAME unit_test COMMAND unit_tests) # default
endif(CMAKE_HOST_WIN32)
```

**Comment by ihhub** [comment]
Hm, let me think about it...

**Comment by ihhub** [comment]
What if we use an enviroment variable which by default is empty and we pass this variable just after `unit_tests` line?
`add_test(NAME unit_test COMMAND unit_tests ${UNIT_TEST_RUN_COUNT})`

**Comment by yannlabou** [comment]
> What if we use an enviroment variable which by default is empty and we pass this variable just after `unit_tests` line?
> `add_test(NAME unit_test COMMAND unit_tests ${UNIT_TEST_RUN_COUNT})`

Still I don’t know how to pass the variable. We are instrumenting the tests via `ctest` calls on appveyor and travis. It seems impossible to do something like `ctest <some_test> ${UNIT_TEST_RUN_COUNT}`.

**Comment by yannlabou** [comment]
Something like `add_test (NAME unit_test COMMAND unit_tests $ENV{UNIT_TEST_RUN_COUNT}` and later in our scripts 
```
set UNIT_TEST_RUN_COUNT=500
ctest ...
```
might work. I’m on holiday til Sunday and can’t really code on my iPad ;). Let me know if this works.

**Comment by ihhub** [comment]
I'll test this later once I have time.
