### ISSUE TITLE
Unit tests are executed twice for AppVeyor

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#243]
Unit tests are executed twice for **AppVeyor** due to [recent changes](https://github.com/ihhub/penguinV/commit/c3b9640825c4b58912a0646cc25b6f94d88b38ee) in CMake. We shouldn't execute `add_test(NAME unit_test_valgrind COMMAND unit_tests 10)` command for AppVeyor and for normal CMake on user's machine.

**Comment by ihhub** [comment]
@yannlabou Do you want to take a look on this bug as it's a continuation of last pull request? :)

**Comment by yannlabou** [comment]
Sure :)

**Comment by ihhub** [comment]
@yannlabou would you be interested becoming a [collaborator](https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account) of the project?

I see that you spend a lot of your personal time to make the project better and I appreciate it very much. If you have a great interest in the project and (as I remember) going to spend some time not only on scripting but in C++ too I would like to make you a collaborator.

Just in case **if** your answer **would be positive**: preferably each issue must be fixed via pull request. To do this you could create a separate branch in the repository. Once work on the branch is done create a pull request which you and other members of the project could review before merging to the **master**. Only very critical and important changes could be committed directly. This rule helps to prevent commit pollution and make easier to track old bugs if they appear :)

I do not demand an answer right now so you could think about it as long as you need ;)

**Comment by yannlabou** [comment]
> @yannlabou would you be interested becoming a [collaborator](https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account) of the project?
> 
> I see that you spend a lot of your personal time to make the project better and I appreciate it very much. If you have a great interest in the project and (as I remember) going to spend some time not only on scripting but in C++ too I would like to make you a collaborator.
> 
> Just in case **if** your answer **would be positive**: preferably each issue must be fixed via pull request. To do this you could create a separate branch in the repository. Once work on the branch is done create a pull request which you and other members of the project could review before merging to the **master**. Only very critical and important changes could be committed directly. This rule helps to prevent commit pollution and make easier to track old bugs if they appear :)
> 
> I do not demand an answer right now so you could think about it as long as you need ;)

@ihhub I really appreciate your offer and I would love to support the project as [collaborator]. I don't have much more time than I spend right now on the project but I'll certainly invest more later.
