### ISSUE TITLE
Change return value of example projects from 0 to 1 and 2

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#247]
All examples in `examples` directory have contain `main` function body which consist of `try ... catch` block:
```cpp
try // <---- do not forget to put your code into try.. catch block!
{
    // code
}
catch( const imageException & ex ) {
    // uh-oh, something went wrong!
    std::cout << "Exception " << ex.what() << " raised. Do your black magic to recover..." << std::endl;
    // your magic code must be here to recover from bad things
    return 0;
}
catch( ... ) {
    // uh-oh, something terrible happen!
    std::cout << "Something very terrible happen. Do your black magic to recover..." << std::endl;
    // your magic code must be here to recover from terrible things
    return 0;
}

std::cout << "Everything went fine." << std::endl;

return 0;
```

We need to modify every code into:
```cpp
try // <---- do not forget to put your code into try.. catch block!
{
    // code
}
catch( const std::exception & ex ) { // uh-oh, something went wrong!
    std::cout << "Exception " << ex.what() << " raised. Closing the application..." << std::endl;
    return 1;
}
catch( ... ) { // uh-oh, something terrible happen!
    std::cout << "Generic exception raised. Closing the application..." << std::endl;
    return 2;
}

std::cout << "Application ended correctly." << std::endl;
return 0;
```

Notable changes:
- return code are different
- we catch `std::exception` instead of `imageException `

**Comment by kgorecki** [comment]
@ihhub what about some cool enumerator for error codes?

**Comment by ihhub** [comment]
Each example has independant code. You're suggesting to duplicate the enumeration in each example. This isn't reasonable.

**Comment by kgorecki** [comment]
I'd rather suggest something like this in some header file to be included in examples
enum class PenguinErrorCodes
{
  NoError = 0,
  GenericException,
  ImageException
};

**Comment by ihhub** [comment]
We print a message before returning something so we could even just return 1 for both cases without enumeration.

**Comment by ihhub** [comment]
We need to keep example code as sumple as possible so people won't turn their backs. Enumeration just complicates a little the understanding of the code if it would be in a separate file or somewhere else.

**Comment by kgorecki** [comment]
Sure, it was just a suggestion. If nobody else wants to get this one, I can take it.

**Comment by ihhub** [comment]
Okay, thanks!

**Comment by ihhub** [comment]
@kgorecki please don't be upset if I wrote something wrong. I've just explain my point of view :)

**Comment by kgorecki** [comment]
@ihhub nah, I'm not upset nor anything like that. I started the discussion just to share opinions ;}

**Comment by ihhub** [comment]
That's cool. We always need more opinions to find the best solution ;)

**Comment by kgorecki** [comment]
Finally... Sorry for a delay, this was hectic week. Getting back to opinion subject - this was exactly the point, to find the best solution ;}

**Comment by ihhub** [comment]
It's okay. No rush :)
