### ISSUE TITLE
Add an example project on Android NDK

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#25]
As the library is cross-platform it would be great to have an example project for Android system.

**Comment by jonny2plates** [comment]
Would like to do this if possible

**Comment by ihhub** [comment]
Yes, sure. But it is better to describe what are you going to do. I prefer if application could grab image, convert it to library format, thresholds and display results. One simple button to grab image and another to threshold. Something like this. But of course if you have better idea it would be great.

**Comment by jonny2plates** [comment]
Ah no problem will tackle this and commit today.

**Comment by ihhub** [comment]
Great! Please do not forget comments for better understand by another people.

**Comment by jonny2plates** [comment]
Sorting before Friday thanks for your patience x

**Comment by ihhub** [comment]
Okay!

**Comment by ihhub** [comment]
Not actual for now
