### ISSUE TITLE
Add a script to output contents of log files within a folder

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#253]
In Travis-CI script (`.travis`) for dynamic analysis we output valgrind results into log files. It's done by MemChecker itself. Currently we output results of log file with fixed name:
```bash
- cat "${TRAVIS_BUILD_DIR}/build/Testing/Temporary/MemoryChecker.2.log" > out && cat out
```
The main attention is on number 2 which is actually hardcoded. It's not a perfect solution.
To avoid this we need to create a script which would find all files with **.log** extension and output all contents of these files.

**Comment by manekenpix** [comment]
Is this one still available?

**Comment by manekenpix** [comment]
I know Hacktoberfest is about to be over, but it's not for that, I just like the project and I'd like to help.

**Comment by ihhub** [comment]
Hi @manekenpix, yes, you could take this issue.

**Comment by manekenpix** [comment]
Thank you, I have a couple of questions.

> To avoid this we need to create a script which would find all files with .log extension and output all contents of these files.

- Output all contents of these files on screen or to another file?
- Do you want to rename the file with a `2` to something else?

**Comment by manekenpix** [comment]
I'm still interested in this one. I recently asked about #397, but I think I'll work on this one first since I asked first. @ihhub did you read my comment?

**Comment by ihhub** [comment]
Hi @manekenpix , I'm sorry for not replying as I missed your previous message. We need to output the content of files to command line/screen.
Right now value 2 is just hardcoded value which means nothing. Instead of this we exactly need to read all files in directory without such hardcoded values.

**Comment by manekenpix** [comment]
I'll give this one a go for this coming Hacktoberfest, if that's ok (sorry about not having worked on it before)

**Comment by ihhub** [comment]
Sure!
