### ISSUE TITLE
Add cmake files for existing example projects

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#261]
We have a bunch of example projects in `examples` directory:
```bash
bitmap_operation
blob_detection
cuda/image_function
cuda/pinned_memory
filters
function_pool
image_function
opencl/image_function
thread_pool
```

We need to add `cmake` files inside each project directory as well as add a simple description how to compile a project with `cmake` inside `README.md` file.

**Comment by yannlabou** [comment]
/pull/271
