### ISSUE TITLE
Remove duplicated function pointer definitions

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#264]
We have original function pointer definitions which are located in `src/image_function>helper.h` These definitions are only for Form 4 of functions (almost each function has 4 forms). We have the same definitions in `test/unit_tests/unit_test_image_function.cpp` and in `test/performance_tests/performance_test_image_function.cpp`. In first file we use all 4 (possible) forms of functions while in second we use only first form. Ideally we need to remove function pointer definitions from test files at all. One of solutions is to declare all function pointers in `src/image_function>helper.h` but we need to make it understandable.

This issue relates to #69

**Comment by MeKot** [comment]
Hello there, @ihhub, I would love to contribute, is this issue still up for grabs?

**Comment by ihhub** [comment]
@MeKot sure, nobody's taken it so it's still open.

**Comment by ihhub** [comment]
@MeKot do you need more explanations or you understand clearly the problem? :) We could fix the issue in multiple steps if final solution is too big.

**Comment by MeKot** [comment]
@ihhub As far as I understand the problem - the definitions for function pointers are to be concentrated in a single file, probably defining a namespace in `src/image_function_helper`. I still am not quite sure about the significance of function forms (is there more to it then just overloading?). And the other thing I am a little vague on is whether the `typedefs` in `namespace Function_Template` are to be kept or refactored out and redefined in `src/image_function_helper.h`.. Thanks for following up, btw :)

**Comment by ihhub** [comment]
I'll give a proper explanation in a few hours. The solution is pretty easy.

**Comment by ihhub** [comment]
`src/image_function_helper.h` file already has such namespace called `namespace FunctionTable`. It contains all full argument function pointers. What we need is to expand it by adding more all variations of each function. Then we could have a single place with functions pointers and use them in test code.

4 forms are just for overloading for ease of development to use the library.

After this we don't need any function pointer declaration in `namespace Function_Template`.

**Comment by MeKot** [comment]
Amazing, it's so much clearer now, I'll submit a pr in a couple of days

**Comment by ihhub** [comment]
Hi, @MeKot . How is it going?

**Comment by MeKot** [comment]
Hi, @ihhub , I am very sorry, but I am only just starting.. Had some issues come up very unexpectedly.. But now I have a few weeks on my hands so I can get some work done.

**Comment by ihhub** [comment]
It's okay. Take your time. At least the know that the work in still on ;)

**Comment by MeKot** [comment]
Hello, @ihhub! Happy holidays! I have had a quick gander and thats what I've come up with #312 Could you have a look at it whenever? The next thing, I guess would be to clean up the `FunctionTable` namespace to just contain functions in the `FunctionForm#` form? If what I've done so far is ok, I could take that on, I guess :)

**Comment by ihhub** [comment]
Hi, @MeKot thanks for your efforts but unfortunately you went by little wrong way: `src/image_function_helper.h` contains now 2 versions of `AbsoluteDifferenceForm4` or `BitwiseAndForm4` for example.

**Comment by ihhub** [comment]
What you need to do is to remove original function pointers in `namespace FunctionTable`.

Yeah, now I see that you mentioned this :) Okay, my bad. So far so good then

**Comment by ihhub** [comment]
@MeKot we're waiting for your clean up code later :)

By the way, if you would like to have in the same direction, you could pick issue #178

**Comment by MeKot** [comment]
@ihhub Hello, so, I've cleaned up the code. Could you have a look at it when you have time? And meanwhile I'm happy to move on to #178

**Comment by ihhub** [comment]
@MeKot there is just one small question of mine in the pull request. Could you please take a look? Thanks for taking #178 issue!
