### ISSUE TITLE
CMake Support of libjpeg

### ISSUE THREAD

**Issue by yannlabou** [ihhub/penguinV#270]
With #45, it is now necessary to provide a support for libpng in various `CMakeLists.txt` files. `find_package(JPEG)` should work on all UNIX platforms. For Windows, similar work has been done in #256.

**Comment by ihhub** [comment]
@yannlabou I found a working code for libjpeg usage. Once you fixed it I'll add that code as well. The original pull request was closed by me as we reached a wall in author's response.
