### ISSUE TITLE
Use the same Qt version for all Travis builds

### ISSUE THREAD

**Issue by yannlabou** [ihhub/penguinV#272]
Building on OS X last much longer than on other platforms due to `QT_BASE=latest`. Homebrew is always busy at downloading the latest Qt formula.
As we are already using Qt 5.9 on Ubuntu, we should set `QT_BASE=59` (Qt 5.9) on OS X.

**Comment by ihhub** [comment]
This is good too to have a same conditions for all builds.

**Comment by yannlabou** [comment]
Won't do. Homebrew is designed to installed the latest version of a formula (package). Currently Qt 5.12.
