### ISSUE TITLE
CMake must fail for example compilation failure

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#274]
We compile unit and performance tests as well as examples on Travis-CI and AppVeyor using CMake. Unfortunately, a compilation failure of any of example doesn't fail overall CMake compilation so we could be unaware of a problem. [This](https://travis-ci.org/ihhub/penguinV/jobs/458336343) is an example of such problem. Check for qt compiled example in the log (line **1265**).

**Comment by ihhub** [comment]
@yannlabou any ideas how to fix it?

**Comment by yannlabou** [comment]
I'll find out! :wrench:
