### ISSUE TITLE
Add a class for line representation in 2D space

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#277]
We have classes to represent a point in 2D and 3D space. Such classes locate in `src/math/math_base.h` file. We want to add a new template class called `LineBase2d`. This class should include following logic:
1. First constructor accepts 2 points of `PointBase2d`
2. Second constructor accepts 1 `PointBase2d` point and angle (in radians)
3. function `angle() const` returns an angle of line
4. function `position() const` returns a point which line intersects
5. function `distance( const PointBase2d & point ) const` returns a distance from point to line

**Comment by yannlabou** [comment]
> @yannlabou would you like to do this? Sorry that I took your initial UI task :(

👍

**Comment by ihhub** [comment]
Otherwise, I would recommend tohave a look at UI visualiser which is easier :)

**Comment by ihhub** [comment]
@yannlabou How is it going? Do you need some skeleton code or explanations? :)

**Comment by yannlabou** [comment]
I still want to do the first implementation on my own. I just have busy days currently. If you need it urgently, sure go ahead.

**Comment by ihhub** [comment]
No-no, it's not urgent :) I asked because I will be on trip for around 2 weeks so I normally would have an access only from my phone... That's why I proposed some help if any needed before I go :)

**Comment by ihhub** [comment]
Good day, @yannlabou , how is it going? :)
