### ISSUE TITLE
Add histogram and projection profile visualizer class based on existing UI Window

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#278]
We have image processing functions to get image histogram as well as projection profile. Such functions return an array (vector) of values. We have a base UI class for visualisation which is located at `src/ui/ui.h` file. We want to create a template function which would create an image based on given input array and display the result in a window. Such function should receive base `UiWindow` class object and `std::vector` as arguments.

**Comment by ihhub** [comment]
@BascoDLowell would you like to have a look into it? It's related to what you have done recently.
If you need more information please ask us :)

**Comment by BascoDLowell** [comment]
Yes, I'm willing to work on this..  👍 
If I understand the requirement, we need a template function to display the output of image histogram and projection transformation in UIWindow? Where should this template function be placed?

**Comment by ihhub** [comment]
Let's create a directory `tool` inside `src/ui` with a file named `tool_ui.h`. As functions are templates we don't need source file (as of now). Call functions as `DisplayHistogram` and `DisplayProjectionProfile`.

**Comment by ihhub** [comment]
The biggest problem which we may face here is the size of projection profile array. Additionally, we need to normalise values in histogram as well. My suggestion for histogram: highest value would have 100 pixels of height. The same applies for projection profile.

From another side we can do not image at all (we still need an image but we create a white N by M pixels image) and all drawings we do via our UI classes. Resizing the image would always make our drawings correct. Unfortunately this method could be slower. What do you think?

**Comment by BascoDLowell** [comment]
I'm not sure I understand completely your thoughts. May I know where is these image histogram and image projection implementations?

**Comment by ihhub** [comment]
In **src/image_function.h** and **src/image_function.h** file you could find *Histogram* and *ProjectionProfile* functions. Histogram always returns a vector of size of 256, while ProjectionHistogram returns variable sized vector.

**Comment by ihhub** [comment]
As both functions return a vector we can just create a single template function called DisplayHistogram which would construct an image based on given input array.

**Comment by ihhub** [comment]
So this task is just to display already obtained/generated results. Nothing more than this :) Is it clear for you now?

**Comment by BascoDLowell** [comment]
Yes, I understand that part. But I don't understand your suggestions in the implementation of Display functions.

**Comment by ihhub** [comment]
The function should looks like this:
```cpp
void DisplayHistogram( UiWindow & window, const std::vector < uint32_t > & histogram )
{
    PenguinV_Image::Image image( histogram.size(), 100 );
    image.fill( 255 );
    window.setImage( image );
    window.drawLine( line1 );
    ...
    window.drawLine( lineN );
    window.show();
}
```

**Comment by BascoDLowell** [comment]
This should be declared virtual and static function right? So we dont have to create an object of the class to call the function, what do you think?

**Comment by ihhub** [comment]
This function should be just as a template function where template parameter is type of vector:
```cpp
template <typename _Type>
void DisplayHistogram( UiWindow & window, const std::vector < _Type > & histogram )
{
    PenguinV_Image::Image image( histogram.size(), 100 );
    image.fill( 255 );
    window.setImage( image );
    window.drawLine( line1 );
    ...
    window.drawLine( lineN );
    window.show();
}
```
So that all code could be located within header (a single function) and it could accept not only `uint32_t` type.

**Comment by ihhub** [comment]
if you are not familiar with templates then just made function declaration in a file and then add function implementation in source file. No harm in this :)

**Comment by BascoDLowell** [comment]
I haven't tried implementing template function but I think I can manage. :)

**Comment by BascoDLowell** [comment]
@ihhub, do we have a way to set and get pixel value of the image?

**Comment by ihhub** [comment]
`image.data()` gives you a raw pointer to whole image. If you want to construct image without any drawings then you have to create RGB image and set needed pixels. Please refer to `src/image_function.cpp` *SetPixel* function.

**Comment by ihhub** [comment]
You can make first iteration of the code and make a pull request so then we can discuss together what we need to do if anything else required :)

**Comment by ihhub** [comment]
Hello @BascoDLowell , how is it going?

**Comment by BascoDLowell** [comment]
Hi @ihhub! I became busy with some urgent things. I'll try to get back to this as soon as I can. :)

**Comment by ihhub** [comment]
Thanks for the answer! We'll be waiting for your implementation :)
