### ISSUE TITLE
Add a makefile for performance tests

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#28]
It is required to add a makefile for performance tests (see performance_tests) folder to support make. Please refer to makefile structure for examples.

**Comment by lakshmanaram** [comment]
@ihhub I'd like to take up this issue. This is my first time creating make files and am planning to reference examples makefiles and this [link](http://www.cs.umd.edu/class/fall2002/cmsc214/Tutorial/makefile.html). Will that be okay ?

**Comment by ihhub** [comment]
@lakshmanaram I recommend to have a look at example projects and their makefiles. It would be very useful for you as a reference.

**Comment by lakshmanaram** [comment]
I am presently trying to work on this issue. I tried running the makefile in unit tests and I am facing this error. 

> g++ build/bin/blob_detection.o build/bin/bitmap.o build/bin/image_function.o build/bin/unit_tests.o build/bin/unit_test_bitmap.o build/bin/unit_test_blob_detection.o build/bin/unit_test_framework.o build/bin/unit_test_helper.o build/bin/unit_test_image_buffer.o build/bin/unit_test_image_function.o -o unit_tests -pthread
build/bin/blob_detection.o: In function `Blob_Detection::BlobDetection::find(Bitmap_Image::BitmapImage<(unsigned char)1> const&, unsigned int, int, unsigned int, unsigned int, Blob_Detection::BlobParameters, unsigned char)':
blob_detection.cpp:(.text+0xf98): undefined reference to `void Image_Function::ParameterValidation<(unsigned char)1>(Bitmap_Image::BitmapImage<(unsigned char)1> const&, unsigned int, unsigned int, unsigned int, unsigned int)'
build/bin/unit_test_helper.o: In function `Unit_Test::fillImage(Bitmap_Image::BitmapImage<(unsigned char)1>&, unsigned int, unsigned int, unsigned int, unsigned int, std::vector<unsigned char, std::allocator<unsigned char> > const&)':
unit_test_helper.cpp:(.text+0x5b4): undefined reference to `void Image_Function::ParameterValidation<(unsigned char)1>(Bitmap_Image::BitmapImage<(unsigned char)1> const&, unsigned int, unsigned int, unsigned int, unsigned int)'
collect2: error: ld returned 1 exit status
Makefile:33: recipe for target 'unit_tests' failed
make: *** [unit_tests] Error 1  

Can you please tell me if I am missing something @ihhub ?

**Comment by ihhub** [comment]
@lakshmanaram Try to update to latest version. I have run just now on my PC (Linux Mint 17.3) and it works perfect.

**Comment by lakshmanaram** [comment]
Line no 21 in unit_tests/Makefile `CXXFLAGS := -std=c++11 -Wall -O2` was the causing the error in my system. I am running Ubuntu 16.04 with updated stable versions of g++ and make. Once I removed -O2 option in the CXXFLAGS, it works like a charm. I am curious as to what it's purpose is?

**Comment by ihhub** [comment]
@lakshmanaram -O2 option is optimization option (maximum speed). For unit tests it is not so important but for performance test it is. Need to verify such option on Unix systems then.
