### ISSUE TITLE
Add Format Step into Build Pipeline

### ISSUE THREAD

**Issue by yannlabou** [ihhub/penguinV#280]
To help maintainers and contributors, a style guideline should be provided and directly ran on Appveyor and Travis CI. We can ensure that all changes are checked for formatting before they are merged into master. [clang-format](http://clang.llvm.org/docs/ClangFormat.html) has been established in the industry as standard tool for code formatting.

**Comment by ihhub** [comment]
I totally agree with this. I wanted to to this long time ago. First of all we need to write a coding style so that people could refer to it. Next step is to implement this coding into script verification tools.

**Comment by yannlabou** [comment]
> I totally agree with this. I wanted to to this long time ago. First of all we need to write a coding style so that people could refer to it. Next step is to implement this coding into script verification tools.

Please create a branch for this issue. We could then draft our ideas in Contributing.md.

**Comment by ihhub** [comment]
Shouldn't it be a separate document? Do you have an access to wiki pages of the project?

**Comment by yannlabou** [comment]
> Shouldn't it be a separate document? Do you have an access to wiki pages of the project?

Sure. A separate document linked in the Contributing page. The wiki might also be a great place for that. Anyway let’s start. :)

**Comment by ihhub** [comment]
[Here](https://github.com/ihhub/penguinV/wiki/Code-style). Can you edit it?

**Comment by yannlabou** [comment]
> [Here](https://github.com/ihhub/penguinV/wiki/Code-style). Can you edit it?

Yes.

**Comment by ihhub** [comment]
Hi @yannlabou , you seem to be very busy these days, don't you? :)

Would you mind to share some ideas of implementation for this issue? Such feature greatly improves pull request reviews and overall code development.

**Comment by yannlabou** [comment]
> Hi @yannlabou , you seem to be very busy these days, don't you? :)
> 
Oy yeah. I'm in a new project at work. Lot of stuff to organize. Little time to code :(
> Would you mind to share some ideas of implementation for this issue? Such feature greatly improves pull request reviews and overall code development.
Sure :).

**Comment by ihhub** [comment]
I think we need to close this issue. We need only one time to check format style which is done in Travis-CI.
