### ISSUE TITLE
Add circle (oval) and rectangle drawing support for UI Window classes

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#282]
We have 3 classes for UI Window:
`src/ui/ui.h` - base class
`src/ui/qt/qt_ui.h` - QT API based class
`src/ui/win/win_ui.h` - Win32 API based class

Currently classes support drawings of points and lines, we need to add functions to support drawings of **ovals** and **rectangles** as well.

This issue relates to #104

**Comment by ihhub** [comment]
Hi @BascoDLowell, would you like to have a look into this issue since you work on QT (and on Windows)? You could make changes for QT as of now (and then later fix for Windows). If you need more information regarding this issue or something is no clear I would gladly help you :)

**Comment by BascoDLowell** [comment]
I'll try this out @ihhub . I like to ask:
Do we have an example for the drawPoint() and drawLine() function in Qt?
This functions should draw to a bitmap image, right? (changing colors in the bitmap stream?)

**Comment by ihhub** [comment]
We already have an implementation of point and line functions for Qt. Please take a look into **src/ui/qt/qt_ui.h** and **src/ui/qt/qt_ui.cpp** files. We use paint tool to draw on canvas and then output it as a bitmap image.

**Comment by BascoDLowell** [comment]
I'm interested on digging on this! I don't have much knowledge on drawing in QT but I have time to read documentations.

**Comment by ihhub** [comment]
I would recommend to have a look into [QPainter documentation](https://doc.qt.io/qt-5/qpainter.html). For ellipse you could use **drawEllipse** while for rectangle you could use a set of **drawLine** calls. I hope it would simplify your work :)

**Comment by BascoDLowell** [comment]
Hey @ihhub ! I finished extending the qt_ui.h classes with ellipse and rectangle. Should I open a Pull Request? or work on Win32 API additional classes?
Can I still use Qt IDE with Win32  API? I'm not sure I know how to add Win32 API to a project. Can you help me?

**Comment by ihhub** [comment]
You could create a pull request for just Qt only if you think it's easy for you. No harm in this.

You can use Win32 API within Qt as this API is OS based API. If I'm wrong you could have a look at Win32 UI example in `examples\windows\edge_detection`.

**Comment by BascoDLowell** [comment]
I noticed when I tried creating a pull request that my fork didn't have your commit when you changed the comments a while ago, can you help me regarding that? How can I add that commit in my fork?

**Comment by ihhub** [comment]
You have to merge your changes with latest changes in trunk. Either you can do this via GitHub application on Windows or you just fork again and replace files which you modified.

**Comment by BascoDLowell** [comment]
Hi @ihhub! Currently, I cannot run the win32 API based example.
I have visual studio 2017 installed. 
I'll be continuing on monday.

**Comment by ihhub** [comment]
Hi @BascoDLowell ,
Could you please find the exact place in code where this exception raises? Did you put an image `examples/_image/mercury.bmp` within a directory where you run your compiled application?

**Comment by ihhub** [comment]
I assume that this exception raises at **line 14**. This line must be removed as it was created for testing only. Could you please do it? After this you could see a message `Cannot load the image` which is a normal behaviour of the application if no image is within directory.

**Comment by BascoDLowell** [comment]
I was able to run the sample by copying `mercury.bmp` to the sample application folder. Thanks!
