### ISSUE TITLE
CPU architecture code verification and instruction set support validation

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#29]
We need a code what checks which CPU architecture it is compiled on, plus all possible supported instructions sets such as SSE, AVX, NEON. Please refer to folder **PenguinV/Library/penguinv** for more information.

**_cpu_identification.h_** file should contain all necessary checks inside by right logic. Now it is empty :(

The idea is once compiled application/library could choose possible supported instruction sets and utilize it without extra magic. First step is to identify CPU architecture on what is compiled. This could be done by macros. Second step is verification supported instruction sets on current platform/architecture.

**Comment by xoorath** [comment]
Hey @ihhub I've done something like this before.... 

https://github.com/xoorath/xo-math/blob/master/xo-math/include/DetectSIMD.h

Can you check and see if it's along the lines of what's needed? If it's in the direction you're looking for, I could take a crack at a pull request and update the appropriate function returns to also check the define (so checks can be made both at runtime and compile time).

**Comment by ihhub** [comment]
Hi, @xoorath . Your code seems correct for detection of supported instruction sets by compilers (we have different ways of detection on Windows :) ). Please make a pull request for review.
