### ISSUE TITLE
Change README file to be more user friendly

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#321]
Our README file is good but it's not the best one. We don't have any specification how to make it better but it seems that it needs some refinement :)

**Comment by vrozin** [comment]
Hello,
I'm new to the project, but would like to help you on this issue.
PR #401 has been submitted with some changes.
Please feel free to ask for further modification =)

**Comment by ihhub** [comment]
Hi @vrozin thank you very much for your efforts! We're looking into your PR.
