### ISSUE TITLE
Float implementation of existing edge detection code

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#328]
We have gradient based edge detection algorithm in `src/edge_detection.h` and `src/edge_detection.cpp` files. This implementation is **double** based. We want to expand the code to support **float** as well. We want to keep an implementation in source file but make `class EdgeDetection` as template. Specifications of this template class would be only `double and `float`.

**Comment by vrozin** [comment]
Hello!
May I contribute to this issue?

**Comment by ihhub** [comment]
Hi @vrozin . Yes, you can do it. Do you need any further explanation?

**Comment by vrozin** [comment]
@ihhub, thank you, at least not yet. The description you gave provides good details on what should be done.
