### ISSUE TITLE
Python module compilation for Python 2 (for Python 3 is done) on AppVeyor

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#348]
We have auto compilation of Python module for Python 3.7 on AppVeyor. We want to add auto compilation for Python 2.7 as well as many people still use this version of Python. What changes we need:
1. Rename **PythonModule** jobs into **Python3.7**
2. Add new jobs named **Python2.7**
3. Add the same logic for Python2.7 as it's done for Python3.7

**Comment by yannlabou** [comment]
It was difficult but I submitted /pull/374.

**Comment by ihhub** [comment]
@yannlabou thank you so much for your efforts! I put few comments there :)
