### ISSUE TITLE
Travis build uses Python 2.7 instead of Python 3.7

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#354]
We build Python module via Travis-CI. The initial intention was to build it for Python 3.7 but from logs we see that the build uses Python 2.7. The issue could lie in a fact that Python version is actually **Python: 3.7 C++** as visible from job info.

**Comment by yannlabou** [comment]
@ihhub  Sure. I'll take care as soon as I have time.

**Comment by ihhub** [comment]
Thank you.

**Comment by ihhub** [comment]
I think we just beed to move **language: cpp** into matrix job to fix this problem.

**Comment by yannlabou** [comment]
Let's see :)
