### ISSUE TITLE
Travis-CI script cleanup (move script portion for one job into separate place)

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#356]
Our script for Travis-CI is *.travis.yml* file. We wan to separate `script` part for static analysis that we don't have such complicated logic at the bottom of the file. We need to just add **-script** section here:
```
    - os: linux
      env: STATIC_ANALYSIS=ON
```
So in result we won't have an extra logic for main **script** section.

**Comment by ihhub** [comment]
Hey @yannlabou, does it make sense to do? :)

**Comment by yannlabou** [comment]
> Hey @yannlabou, does it make sense to do? :)

Sure.

**Comment by ihhub** [comment]
I'm sorry if I request too many things from you. After all, it's a volunteer work so I have no right to force anyone to do anything :)
