### ISSUE TITLE
SIMD implementation of Flip() function 

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#357]
We do not have SIMD (SSE, AVX or NEON) implementation of **Flip()** function. For the person who is willing to add such code please take a look into an implementation of the function inside `image_function.cpp` and the structure which is used for SIMD code inside `image_function_simd.cpp`. Please do not forget to add unit test for newly created function(s) inside `unit_test_image_function.cpp` (it's just one line code via macros call).

**Comment by ihhub** [comment]
Hi @0x72D0 , would you like to have a look into this issue? I think we could implement it for horizontal flip at least which is still better than nothing. What do you think?

**Comment by ihhub** [comment]
Hello @0x72D0 do you have a spare time for have a look into this? :)

**Comment by 0x72D0** [comment]
I'm gonna check this this weekend :)

**Comment by ihhub** [comment]
Sure. Looking forward for the implementation!

**Comment by 0x72D0** [comment]
with my test, I get the following error:
![screenshot_2019-02-17_11-45-57](https://user-images.githubusercontent.com/16087328/52916126-cd7e9e80-32a9-11e9-8e71-52f438785b80.png)
any idea why this error trigger?

**Comment by ihhub** [comment]
Original Flip function works only with gray-scale images so the problem could lie in VerifyColorImage instead of correct VerifyGrayScaleImage usage.

**Comment by ihhub** [comment]
You just post a code for `Flip` function from `namespace simd` which you made and I take a look :)

**Comment by 0x72D0** [comment]
from the simd namespace:

![screenshot_2019-02-17_22-49-55](https://user-images.githubusercontent.com/16087328/52927030-81157c00-3306-11e9-84b0-613c35666fd1.png)

from the sse namespace (for now I try to make the horizontal only working):

![screenshot_2019-02-17_22-50-29](https://user-images.githubusercontent.com/16087328/52927059-a0aca480-3306-11e9-9714-3f232d6a5f2a.png)

**Comment by ihhub** [comment]
You call `ConvertToRgb` inside code which is wrong.

**Comment by 0x72D0** [comment]
oh yeah you're right... didn't see it...

**Comment by 0x72D0** [comment]
but still it shouldn't be the problem since when I test sse, these lines are not executed

**Comment by ihhub** [comment]
Unit tests generate image which could have width less than 16 bytes leading to execution of CPU path code.

**Comment by 0x72D0** [comment]
oh ok, I will ran the test and see if the output change

**Comment by 0x72D0** [comment]
yup everything is fine now

thanks :)

**Comment by ihhub** [comment]
@0x72D0 I assume that AVX implementation would be not easy, wouldn't it? :)

**Comment by 0x72D0** [comment]
exactly :)

**Comment by 0x72D0** [comment]
same problem each time, I can't shuffle hi and low part of the ymm registers

**Comment by ihhub** [comment]
I understand. Would you like to try some of tasks related to multithreading or implement some of filters with SIMD?

**Comment by 0x72D0** [comment]
I'm gonna try something else

**Comment by ihhub** [comment]
Closing this issue as AVX implementation does not look to be straightforward and we are not going to do it in near future.
