### ISSUE TITLE
Add missing function registration for ConvertToRgb SIMD function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#358]
In`src\image_function_simd.cpp` we have a registration structure **FunctionRegistrator** where we register functions to be used everywhere across the library. We forgot to add `ConvertToRgb` function.

**Comment by ihhub** [comment]
@0x72D0 could you please add this function and run unit and performance tests for it? Now function pool shouldn't have 5x slower performance than SIMD :)

**Comment by 0x72D0** [comment]
sorry... I completly forgot about it...
