### ISSUE TITLE
Implement multithreaded version of Split() function (based on existing thread pool code)

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#364]
We do not have function pool (multithreading based on thread pool) implementation of **Split()** function. For the person who is willing to add such code please take a look into an implementation of the function inside `image_function.cpp` and the structure of code for function pool inside `function_pool.cpp`. Please do not forget to add unit test for newly created function(s) inside `unit_test_image_function.cpp` (it's just one line code via macros call).

**Comment by theoniko** [comment]
Hello @ihhub,

Could i work on this issue? Is there a similar older pull request to use as reference?

**Comment by ihhub** [comment]
Hi @theoniko , I'll make some preparation changes for this and explain in details what to do. We don't have a similar pull request but we have [similar commit ](https://github.com/ihhub/penguinV/commit/9c2a7b7f76153a43add904cc733270d0dc8da6dc).

**Comment by theoniko** [comment]
I plan to split this issue to the following tasks:

1. Add declaration of all overloaded function version of Split() (2 functions in total) in function_pool.h
3. Define Split task in FunctionTask class(add it  to  enum TaskName and in list of image functions) in function_pool.cpp
2. Implement all the overloads of Slipt in the list of global functions in function_pool.cpp
4.  Update the API_description for Split functio(add namespace Function_Pool
5.  Add unit tests

If everything is fine, i will open an initial pull request with some commits that cover the above tasks.

My open points are 
- how to do the unit test based on macro ?
- if there is needed any change in  InputInfo or OutputInfo structs? 
From the API_description.md for Split i think no change is needed

**Comment by ihhub** [comment]
Hi @theoniko , you're totally correct. In unit tests you just need to add one line of code in **namespace function_pool**. No need any changes in structures.
