### ISSUE TITLE
Cuda implementation of ProjectionProfile() function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#371]
We have CPU implementation of **ProjectionProfile**() function in `src/image_function.h` and `src/image_function.cpp` files. We want to add Cuda implementation of the same function. Please put new code in `src/cuda/image_function_cuda.cuh` and `src/cuda/image_function_cuda.cu` files. Things which we need to do:
1. Copy 4 function declaration from `src/image_function.h` to `src/cuda/image_function_cuda.cuh`
2. Copy first 3 function implementation from `src/image_function.cpp` to `src/cuda/image_function_cuda.cu`
3. Add Cuda kernel called `normalizeCuda` into unnamed namespace at the top of `src/cuda/image_function_cuda.cu` file
4. Add forth function implementation by following **LookupTable()** code logic

**Comment by sukhbeersingh** [comment]
Hey I would like to have a go at this issue.

**Comment by ihhub** [comment]
Sure!
