### ISSUE TITLE
Add unit tests for Shift() function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#372]
We have an implementation of **Shift**() function in `src/image_function.h` and `src/image_function.cpp`. Our unit tests locate in `test/unit_tests/unit_test_image_function.cpp`. We do not have unit tests for this function. What we need to do is to add 4 unit test functions to cover 4 different types of Shift() function. Please refer to Invert() function as an example.

**Comment by theoniko** [comment]
i had a look in the unit_test_image_function.cpp file and the unit tests for Shift() function are already implemented (refer to  form1_Shift, form2_Shift, form3_Shift and form4_Shift).

**Comment by ihhub** [comment]
Hi @theoniko , you're totally right, functions are there already. Thank you very much for poining this out!
