### ISSUE TITLE
Add support for Mingw compiler

### ISSUE THREAD

**Issue by BascoDLowell** [ihhub/penguinV#376]
I'm trying to compile the sample project in examples/qt_framework/qimage_display, and I got 2 errors stating '_cpuindex' was not declared in scope. I'm compiling in Qt.

I am also interested in contributing code (the reason I'm trying the example), can someone help me started?

**Comment by ihhub** [comment]
Hello @BascoDLowell could you please paste here exact compilation errors? It would greatly help to identify the root of problem.

**Comment by ihhub** [comment]
Which are would you like to contribute in? We have UI, GPU, SIMD, code optimisation, code cleanup or even documentation? :)

**Comment by ihhub** [comment]
@BascoDLowell plus could you please state your OS as well and development environment?

**Comment by BascoDLowell** [comment]
![penguinerrorimage](https://user-images.githubusercontent.com/14083887/52552368-e6570200-2e1a-11e9-9e2f-ea4d041a8547.JPG)

**Comment by ihhub** [comment]
I assume you use Windows. Give me please 2-3 hours until I get an access to Windows machine to check the issue. Thank you for sharing it!

**Comment by BascoDLowell** [comment]
My OS is Windows 7. I use Qt 5.6 with mingw compiler.

**Comment by ihhub** [comment]
I think the problem lies in the compiler. It might not support such functions...

**Comment by ihhub** [comment]
@BascoDLowell could you please try to use another compiler to verify such problem?

**Comment by BascoDLowell** [comment]
I have an installer for Qt 5.7 with built-in msvc 2015 compiler. I'll try that one.

**Comment by ihhub** [comment]
Please try this trick: in `src/penguinv/cpu_identification.h` file change line 6 `#ifdef _WIN32 // Windows` into `#if defined(_WIN32) && !defined (__MINGW32__)`.
Currently workflow was tested only for Visual Studio compiler on Windows.

**Comment by BascoDLowell** [comment]
Sorry, I lost my previous qt installation. I also cannot run the example with Qt 5.7.1 with MSVC2015 compiler.I got this message:
Error while building/deploying project example_qimage_display (kit: Desktop Qt 5.7.1 MSVC2015_64bit)
When executing step "qmake"

**Comment by BascoDLowell** [comment]
I'll get back to this tomorrow.

**Comment by ihhub** [comment]
Okay. Let's wait for your tomorrow's test :)

**Comment by ihhub** [comment]
Hi @BascoDLowell, could you please try to replace line **6** in `src/penguinv/cpu_identification.h` by this code:
```cpp
#if defined(_MSC_VER) // Visual Studio
```
It should help to fully solve your first problem.

**Comment by BascoDLowell** [comment]
![image](https://user-images.githubusercontent.com/14083887/52603207-d97cf180-2ea0-11e9-85ee-74148f5cf8a1.png)
I replaced cpu_identification.h and used mingw53_32 compiler in Qt.

**Comment by ihhub** [comment]
My apology. Please replace line **21** by:
```cpp
#elif defined(__APPLE__) || defined(__linux__) || defined (__MINGW32__)
```

**Comment by BascoDLowell** [comment]
Using MSVC2017 compiler and editing _src/penguinv/cpu_identification.h_ at line 6,
I was able to run the example.
I'll try changing line 21 and use mingw again.

**Comment by ihhub** [comment]
This is a good sign :)

**Comment by BascoDLowell** [comment]
It worked on mingw compiler. Thanks!

**Comment by ihhub** [comment]
Well done @BascoDLowell ! Could you please create a pull request with these 2 lines of code to fix this issue?

**Comment by BascoDLowell** [comment]
This is my first time, Can you tell me exactly what I need to do. Currently my fork is 1 commit behind this repository.

**Comment by ihhub** [comment]
If you follow [this link](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) you should be able to create a pull request within your forked repository. Set a name of pull request the same as this issue. The rest of stuff I'll do myself :)

**Comment by BascoDLowell** [comment]
@ihhub, Please check my pull request. thanks!
