### ISSUE TITLE
Python compilation sometimes fails on AppVeyor

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#385]
We observed multiple compilation failures for Python on AppVeyor. Rerun of such builds helps. I will attach a log once the failure happens again.

**Comment by ihhub** [comment]
@yannlabou have you noticed this on your fork? I will put log file once I see it.

**Comment by yannlabou** [comment]
> @yannlabou have you noticed this on your fork? I will put log file once I see it.

Both python jobs? I'm building only my pull requests. I will observe this. Logs might also be indeed helpful.

**Comment by ihhub** [comment]
One time I saw Python build for 2.7, another time for 3.7.

**Comment by ihhub** [comment]
Check [this](https://ci.appveyor.com/project/ihhub/penguinv/builds/22444726) log.

**Comment by yannlabou** [comment]
Could you pass `-dv` (debug and verbose) to choco install and report? https://github.com/ihhub/penguinV/blob/482aa69c9a801c95666cc6cb5e95acf8e6560578/appveyor.yml#L38

**Comment by ihhub** [comment]
I'll do it in a while.

**Comment by ihhub** [comment]
Do you mean to make
`- if not exist C:\ProgramData\chocolatey\bin\swig.exe choco install swig --version 3.0.12 --yes --limit-output -dv`?

**Comment by yannlabou** [comment]
Yes.

**Comment by ihhub** [comment]
`-dv` or `--dv`? :)

**Comment by yannlabou** [comment]
`-dv`.

**Comment by ihhub** [comment]
Done.

**Comment by yannlabou** [comment]
Let’s see what it outputs during build failures.

**Comment by ihhub** [comment]
[Here](https://ci.appveyor.com/project/ihhub/penguinv/builds/22752772/job/6jdpc6kavle1a96w) is our catch :)

**Comment by yannlabou** [comment]
There is nothing we could do. It looks like a Powershell/Chocolatey timeout (temporary network issues?). 
There is a `chocolatey` timeout option but I don't believe it's necessary to increase the build time for occasional failures.
```
--timeout, --execution-timeout=VALUE
     CommandExecutionTimeout (in seconds) - The time to allow a command to 
       finish before timing out. Overrides the default execution timeout in the 
       configuration of 2700 seconds. '0' for infinite starting in 0.10.4.
```

**Comment by ihhub** [comment]
In this case we really can nothing to do :)
