### ISSUE TITLE
Include CUDA examples into CMake compilation

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#408]
[Recently](https://github.com/ihhub/penguinV/commit/f3f3640ffeb279853de697372e7bdcad29637306) we added **CUDA** compilation support into CMake. We have few Cuda examples: `examples/cuda/image_function/` and `examples/cuda/pinned_memory/` which we would like to add as a part of CMake.

**Comment by ihhub** [comment]
Hi @yannlabou is it hard to do?

**Comment by yannlabou** [comment]
It shouldn't be harder than
````
if (CUDA_FOUND)
   add_subdirectory(examples/cuda/image_function)
   add_subdirectory(examples/cuda/pinned_memory)
endif(CUDA_FOUND)
````

In the named subdirs, create CMakelists.txt files with roughly something like
````
cuda_add_executable(image_function example_image_function.cpp)
````

Given the limited amount of time I actually have, I think it's good to let newcomers take care of it.
