### ISSUE TITLE
Sequencial call of find() function for edge detection doesn't clean previous data

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#414]
Edge detection code which locates in **src/edge_detection.h** and **src/edge_detection.cpp** files has *find()* function. Sequencial call of this function doesn't clean previous data.

**Comment by ihhub** [comment]
Hi @vrozin , since you have an interest to work on edge detection would you mind to look into this issue? It's just to call `clear()` function of 2 `std::vector` members of EdgeDetection class :)

**Comment by vrozin** [comment]
Absolutely :)
Consider it being done. I'll apply the change while working on #346
