### ISSUE TITLE
Remove duplication code in BlobInfo class

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#427]
Our blob detection code locates in `src/blob_detection.h` and `src/blob_detection.cpp` files. There are 2 functions which have the same code: **BlobInfo::_getElongation()** and **BlobInfo::_getLength()**. Steps are needed to be done:
1. In **class BlobInfo** add a new parameter called `Value < double >_guideAngle;`
2. In **BlobInfo::_getLength()** function calculate such angle (see the code in **_getElongation** function)
3. In **BlobInfo::_getElongation()** remove existing code to calculate length and angle and replace it with call of **_getLength()** function.

This issue relates to #69

**Comment by FrankJWH** [comment]
If this is still a viable ticket, I'd like to take a shot at it!

**Comment by FrankJWH** [comment]
The one issue I have refactoring this is that both functions are dependent on [_Point2d startPoint_](https://github.com/ihhub/penguinV/blob/d5bc1a3a795c48fa41e60cdfccc79259bb24bc46/src/blob_detection.cpp#L203) as you can see for [here](url) for **BlobInfo::_getElongation** function and [here]() for **BlobInfo::_getLength**.  Do you suggest creating a member variable for it?

**Comment by ihhub** [comment]
Hi @FrankJWH , yes, this issue is still available and it would be great if you fix it.

I have a better idea: we could create a function unnamed namespace (at the top of `blob_detection.cpp` file which would have such signature:
```cpp
double findLengthFromCountour( const std::vector < uint32_t > & contourX, const std::vector < uint32_t > & contourY, double & length Point2DBase< uint32_t > & start, Point2DBase< uint32_t > & end )
{
    // here we put our logic
}
```

The function returns length value. We need to verify input data and throw an exception if the sizes of contours are not equal. Assign (0, 0) to start and end points if the size of contour is less than 2. Please not that **start** and **end** are *uint32_t* based points. We don't need type conversion during cycle runtime like it's done now.

Is it a clear explanation? :)

**Comment by FrankJWH** [comment]
Yes I believe I understand what you're getting at. I was thinking of creating a function and wanted to follow your coding style and form. I'll get that done as soon as possible!

**Comment by ihhub** [comment]
Sure!
