### ISSUE TITLE
Remove PENGUINV_BUILD_TEST enviroment variable for CMake

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#430]
We have `PENGUINV_BUILD_TEST` variable which is used in Travis build for CUDA. There is no evidence that this variable brings any effect on compilation. This is full list of files where this variable appears:
```bash
.travis.yml
CMakeLists.txt
test/performance_tests/README.md
test/unit_tests/README.md
```

**Comment by ihhub** [comment]
Greetings, @yannlabou would you mind to take a quick look into this tiny issue and tell if this variable is truly not in use anymore? :)

**Comment by yannlabou** [comment]
@ihhub Sure. Let me check.

**Comment by yannlabou** [comment]
The variables `PENGUINV_BUILD_TEST` (and `PENGUINV_BUILD_EXAMPLE`) are defaulted to `ON` and not further used in _our_ build jobs. Nevertheless, they are not useless as they give the option to either build or not the tests (and the examples).
e.g. `cmake -DPENGUINV_BUILD_TEST:BOOL=OFF ..` won't generate the CMake targets `performance_tests` and `unit_tests`.

Still there is a subtle bug in https://github.com/ihhub/penguinV/blob/7d0151a1f9e28492570dc57af927ddad8044377d/CMakeLists.txt#L29 and https://github.com/ihhub/penguinV/blob/7d0151a1f9e28492570dc57af927ddad8044377d/CMakeLists.txt#L35.

I strongly believe, it should be 
`if(${PENGUINV_BUILD_TEST} AND (CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR))` 
and 
`if(${PENGUINV_BUILD_EXAMPLE} AND (CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR))`.

**Comment by ihhub** [comment]
Thanks for the detailed research! I'll do a pull request for above bug once I have a spare time.

**Comment by yannlabou** [comment]
> Thanks for the detailed research! I'll do a pull request for above bug once I have a spare time.

/pull/432
