### ISSUE TITLE
SIMD implementation of ConvertTo16Bit() and ConvertTo8Bit() function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#431]
Recently we added **ConvertTo16Bit()** and **ConvertTo8Bit()** functions into our code (`src/image_function.h` and `src/image_function.cpp` files). We would like to implement SIMD (SSE, AVX and NEON) version of these functions which should be located in `src/image_function_simd.h` and `src/image_function_simd.cpp` files. We recommend to have a look into **ConvertToRgb()** function implementation as a reference.

**Comment by ihhub** [comment]
Hi @0x72D0 would you like to try this?

**Comment by 0x72D0** [comment]
@ihhub Yeah sure!

**Comment by ihhub** [comment]
Thanks!

**Comment by ihhub** [comment]
Hi @0x72D0 do you need some help for this issue if any?

**Comment by 0x72D0** [comment]
Hi @ihhub how can I make test function for ConvertTo16Bit?

**Comment by 0x72D0** [comment]
also is it normal if ConvertTo16Bit is not in the function registrator?

**Comment by ihhub** [comment]
Let me think about unit test. I'll come back with solution soon. No, it's not in function registrator as well :(

**Comment by 0x72D0** [comment]
@ihhub I can make a pull request with what I have for now if you want?

**Comment by ihhub** [comment]
Let's do it! We could easily synchronise with master branch after.

**Comment by ihhub** [comment]
Hi @0x72D0 , did you have a time for NEON implementation?

**Comment by 0x72D0** [comment]
@ihhub I will try working on it next month.
