### ISSUE TITLE
Compile edge_detection example for Unix system with X11 support

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#438]
We have `edge_detection` example which locates in `examples/edge_detection` directory. Currently `examples/CMakeLists.txt` compiles this example when Microsoft Visual Studio is present. We need to compile this example if X11 present. Additionally, we need to modify examples/edge_detection/CMakeLists.txt` to compile the example properly for **X11** case.
This issue relates to #285

**Comment by yannlabou** [comment]
/pull/445
