### ISSUE TITLE
Change PENGUINV_DISABLE_PNG_SUPPORT into PENGUINV_ENABLE_PNG_SUPPORT

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#444]
Currently in `src/file/png_file.cpp` we use a macro **PENGUINV_DISABLE_PNG_SUPPORT** to disable PNG code. We detect png library presence in CMake.
From user perspective who wants to use makefile or Visual Studio project or something else such flag doesn't exist by default which leads to compilation error.
If we set a flag **PENGUINV_ENABLE_PNG_SUPPORT** for opposite case in CMake and we change logic in source file then we could provide better user experience :)

**Comment by ihhub** [comment]
Hi @yannlabou what do you think?

**Comment by yannlabou** [comment]
Makes indeed sense.

**Comment by ihhub** [comment]
Okay, I'll do.
