### ISSUE TITLE
Cuda implementation of IsEqual() function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#450]
We have CPU implementation of **IsEqual**() function in `src/image_function.h` and `src/image_function.cpp` files. We want to add CUDA implementation of the same function. Please put new code in `src/cuda/image_function_cuda.cuh` and `src/cuda/image_function_cuda.cu` files. Things which we need to do:
1. Copy 2 function declarations from `src/image_function.h` to `src/cuda/image_function_cuda.cuh`
2. Copy first function implementation from `src/image_function.cpp` to `src/cuda/image_function_cuda.cu`
3. Add Cuda kernel called `isEqualCuda` into unnamed namespace at the top of `src/cuda/image_function_cuda.cu` file
4. Add second function implementation by following **Invert()** code logic

**Comment by fullset** [comment]
@ihhub Can I work on this issue?

**Comment by ihhub** [comment]
@fullset sure, you can!
