### ISSUE TITLE
Disable check for a comment at the end of namespace during static analysis

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#455]
We use a custom Clang format file (`.clang-format`) to specify our code style. Currently we noticed that this format requires a comment at the end of namespace with namespace name which is redundant. We would like to remove such check to avoid false alarm like it's done for example in [this build](https://travis-ci.org/ihhub/penguinV/jobs/532101532) (lines 360 and 376).

**Comment by ihhub** [comment]
Hey @yannlabou do you know fast solution for this? :)

**Comment by yannlabou** [comment]
I think `FixNamespaceComments: false` should do the job in https://github.com/ihhub/penguinV/blob/29f2ea3da83c771652932991171be19a54c1586b/.clang-format#L43. We'll need to test.

**Comment by ihhub** [comment]
I made a separate branch and test commit for this. Let's see...
