### ISSUE TITLE
Optimise Dilate() function performance

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#463]
We have **Dilate()** function in `src/image_function.cpp` under unnamed namespace. There are places where we could potentially speed up function's execution:
1. after reaching the condition `if( imageXEnd - imageX < dilateX )` or `if( height - rowId < dilationY )` we should stop loop as we reached end of line/column.
2. Initialize `const uint32_t rowSize = image.rowSize();` only once
3. Add check if `dilationX` and `dilationY` are equal to 0 then exit function

Additionally, as a part of future commit please remove one empty line before `if( dilationX > width / 2 )`.

**Comment by theoniko** [comment]
Hello @ihhub,
Could i work on this issue?

**Comment by ihhub** [comment]
Hi @theoniko , yes you could :)

**Comment by ihhub** [comment]
Hi @theoniko , are you going to fix this issue as well?

**Comment by theoniko** [comment]
Hi @ihhub 
yes, i will try to fix it during the upcoming weekend.
