### ISSUE TITLE
Merge CUDA and Qt jobs for Linux in Travis-CI

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#469]
Since we are going to expand unit tests and add more jobs (potential ARM support) we need to care about overall job execution time which is currently at around 1 hour. We could merge first 2 jobs which run on Linux machines for Cuda and Qt support. In such case we reduce execution time as we do not run unit tests twice.

**Comment by ihhub** [comment]
Hi @yannlabou , would you mind to take a look at this issue after if you have time?

**Comment by yannlabou** [comment]
This should be doable. I will do that. Not sure if this week but I will.

**Comment by ihhub** [comment]
@yannlabou thanks a lot for taking this issue!
