### ISSUE TITLE
Default memory allocator for main ImageTemplate class

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#483]
We have main image class in `src/image_buffer.h` file called **ImageTemplate**. This class is based on dynamic image allocation and deallocation of CPU memory. Memory allocation and deallocation on high-performance systems with small amount of data do not impact overall performance but on low-performance system it might take some time. We already have a base class for memory allocator in `src/memory/memory_allocator.h` file. We need to write a child class based on heap memory usage: **new** and **delete** operators.

**Comment by ihhub** [comment]
Hi @0x72D0 could you please help me with such issue? I need your data from performance tests on Raspberry Pi before this change :)

**Comment by 0x72D0** [comment]
@ihhub yeah no problem, I can test it tomorrow. Is it the arm branch?

**Comment by 0x72D0** [comment]
[test_output.txt](https://github.com/ihhub/penguinV/files/3258099/test_output.txt)

**Comment by ihhub** [comment]
Hi @0x72D0 . I was little wrong about performance tests. There would not almost no effect in performance while for unit tests on my machine it does. With memory allocator unit tests run in 2 times faster.

Could you measure overall unit tests execution (let's say with iterations of 100) and compile memory_allocator branch and do the same?

**Comment by 0x72D0** [comment]
Hi @ihhub I've done the test on the unit_test with the time command and 100 iteration. It give me the following result on the master branch:
```
real	10m38.131s
user	7m23.711s
sys	5m43.487s
```

**Comment by 0x72D0** [comment]
this is on the memory allocator branch:
```
real	8m0.461s
user	9m9.171s
sys	1m20.865s
```

**Comment by ihhub** [comment]
So as I understand `real` is what we need to compare. Is it correct?

**Comment by ihhub** [comment]
@0x72D0 the only I don't understand is why `user` time for memory_allocation branch is more than for master.

**Comment by 0x72D0** [comment]
user is also more than real so it might only because of a background process or daemon

**Comment by 0x72D0** [comment]
yes what you have to compare is more the `real` time

**Comment by ihhub** [comment]
@0x72D0 cool! Then we can conclude that memory allocator improves performance.

**Comment by ihhub** [comment]
Travis-CI build goes from average 57 minutes to 50 minutes with memory allocator.

**Comment by 0x72D0** [comment]
that's a nice performance boost :)

**Comment by 0x72D0** [comment]
@ihhub wait if I understand well the memory allocator, it's mapping a pre allocated space in memory for the image to go. So can we try to make this memory space aligned to boost SIMD speed?

**Comment by ihhub** [comment]
Yes, we could make it as aligned memory.

**Comment by ihhub** [comment]
@0x72D0 , As I correctly understood we want to have 32-byte aligned allocated memory, don't we?

**Comment by ihhub** [comment]
It's done. You can try to test the difference in speed for unit tests as well for performance but don't forget to allocate memory for second case.

**Comment by ihhub** [comment]
@0x72D0 I've added default memory allocation for performance tests as well.

**Comment by ihhub** [comment]
I ran performance tests and results are very promising :)

**Comment by 0x72D0** [comment]
@ihhub it's normally a 16-byte aligned memory, but 32-byte will do just fine since it's a multiple of 16. Nice now #255 is even more interesting :)

**Comment by 0x72D0** [comment]
oh no sorry 16-byte alignment is for SSE and neon, AVX require 32-byte alignment.

**Comment by ihhub** [comment]
I did 32 byte alignment. Could you please test it? :)

**Comment by 0x72D0** [comment]
@ihhub on raspberry pi with the same way?

**Comment by ihhub** [comment]
On Raspberry Pi for performance tests on master and on memory_allocator branches. I got a performance for some of functions. I assume it depends on image allocation on master branch source code.

**Comment by 0x72D0** [comment]
here's the performance test for memory allocator on raspberry pi:
[test_output.txt](https://github.com/ihhub/penguinV/files/3266586/test_output.txt)

all the neon function seem to be faster, but not the normal function...

**Comment by ihhub** [comment]
Are all functions faster with memory allocator or only neon based?

**Comment by ihhub** [comment]
Yes, you can think about #255 ;) We have a right direction for simd

**Comment by 0x72D0** [comment]
If you compare the first test I made on the master branch and the test I just made on the memory_allocator branch. Only neon based function seem faster

**Comment by ihhub** [comment]
Memory allocator doesn't affect on normal functions as we don't allocatate/deallocate data during performance tests while for neon aligned data is very important which gives the boost.
