### ISSUE TITLE
Rename variables containing chunck into chunk (spelling fix)

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#489]
We have 4 files where such spelling issue appear:
```
src/cuda/cuda_memory.cuh
src/memory/cpu_memory.h
src/memory/memory_allocator.h
src/opencl/opencl_memory.h
```

The task as easy as it looks: just remove letter **c** before _k_ from each appearance of chunck.

**Comment by davidwilson3** [comment]
Submitted PR to fix this issue: [here](https://github.com/ihhub/penguinV/pull/493)
