### ISSUE TITLE
Add Windows build for Travis-CI

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#497]
We already have builds for Linux and OSX systems for Travis-CI. We would like to add build for [Windows](https://docs.travis-ci.com/user/reference/windows/) as well in Travis-CI to support all platforms. In future we might drop AppVeyor support due to inability to support parallel builds.

**Comment by ihhub** [comment]
Hi @yannlabou , did you have a chance to have a look into this issue?

**Comment by yannlabou** [comment]
Yes, I did. I had trouble installing CUDA. I'll follow up when I have more time.
https://github.com/yannlabou/penguinV/tree/issue-497-travis-add-windows-build

**Comment by ihhub** [comment]
I'll have a look into it today's evening

**Comment by ihhub** [comment]
Shall we go without CUDA installation first? We could make it later. Instead of covering everything in one shot we could do it step by step. No harm in this. What do you think?

**Comment by yannlabou** [comment]
Definitely a good start. Caching installed libraries like Qt or something else will then be further milestones.

**Comment by ihhub** [comment]
Yes. Could you please make a pull request without Qt?
