### ISSUE TITLE
Fix makefile for unit tests (lpng and ljpeg flags)

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#509]
We have `test/unit_tests/Makefile` which contains `-lpng -ljpeg` flags for linking. If OS doesn't have such libraries we fail the compilation which we shouldn't do. The solution for this is to use an extra code like:
```
PNG_EXISTS = $(shell ldconfig -p | grep libpng)

ifneq ($(PNG_EXISTS),)
CXXFLAGS += -D PENGUINV_ENABLED_PNG_SUPPORT
LIBS += -lpng
endif
```

Just after settings all variables inside the file.

**Comment by ihhub** [comment]
Hi @fullset , could you please take a look into this issue? It's similar what you have fixed previous time.

**Comment by fullset** [comment]
Hello, @ihhub.
Sure, but give me a couple of days.
