### ISSUE TITLE
Add CUDA implementation of SetPixel() function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#538]
We have an implementation of **SetPixel()** function for CPU which is stored in `src/image_function.h` and `src/image_function.cpp` files. This function has 2 overloads: one to setup one pixel only and another one is to setup an array of pixels. We would like to add the same function for **CUDA** code. We need to store this code in `src/cuda/image_function_cuda.cuh` and `src/cuda/image_function_cuda.cu` files.

**Comment by gkarlos** [comment]
Hey, i was thinking of having a go on this. Are you looking for some sort of optimized kernel, or will a straightforward (somewhat naive) kernel do?

**Comment by ihhub** [comment]
Naive kernel is enough for now.

**Comment by gkarlos** [comment]
@ihhub quick question. Should SetPixel update the Image in place just like the CPU version?

**Comment by ihhub** [comment]
@gkarlos yes, indeed. We could assume that image is very big so copying it is a bad idea.
