### ISSUE TITLE
Add OpenCL implementation of SetPixel() function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#539]
We have an implementation of **SetPixel()** function for CPU which is stored in `src/image_function.h` and `src/image_function.cpp` files. This function has 2 overloads: one to setup one pixel only and another one is to setup an array of pixels. We would like to add the same function for **OpenCL** code. We need to store this code in `src/opencl/image_function_opencl.h` and `src/opencl/image_function_opencl.cpp` files.

**Comment by josephnicholas** [comment]
@ihhub I would like to work on this issue. Thanks

**Comment by ihhub** [comment]
Sure! Let us know if you need any help for this :)

**Comment by josephnicholas** [comment]
@ihhub my apologies on this very late update. I was really swamped with travels during the weekend I just sat down to read the code. My questions below are as follows:

- Do I need to familiarize with the OpenCL library to implement this?
- Another is, as you have said in the description that the CPU implementation is already there, am I correct to assume that migrating from CPU to OpenCL would be the approach(assuming that some functions in OpenCL and CPU are quite the same when comparing)
- Also, I would like to know the approach on testing and what would be the correct test for this.

Thanks.

**Comment by ihhub** [comment]
- No
- CPU implementation is pure C++ code. OpenCL implementation would work on CPU and GPU. Both implementations must produce the same result
- unit test will be tricky. It requires some changes in OpenCL unit test helper code

Let's come to unit test problem after the code is ready and I help with it.

**Comment by josephnicholas** [comment]
@ihhub Thanks, I will work on #544 first then this one. :)

**Comment by josephnicholas** [comment]
@ihhub forgot about this one, since #544 is merged how do I continue on this?

**Comment by ihhub** [comment]
@josephnicholas now you have all needed functions to unit tests for `SetPixel` function. You can refer to `test/unit_tests/unit_test_image_function.cpp` file for logical implementation of the test. We can do this in 2 steps: first create functions, create pull request. If everything is fine then create unit tests for them. Does it sound reasonable?

**Comment by josephnicholas** [comment]
> @josephnicholas now you have all needed functions to unit tests for `SetPixel` function. You can refer to `test/unit_tests/unit_test_image_function.cpp` file for logical implementation of the test. We can do this in 2 steps: first create functions, create pull request. If everything is fine then create unit tests for them. Does it sound reasonable?

Yes, sure, I think I can also learn about it that way. Cheers!

**Comment by josephnicholas** [comment]
@ihhub some few questions that I want to make sure when I do a PR.

- `SetPixel()` in CPU code will be directly copied to OpenCL for the same implementation, am I right? If so, can we make `SetPixel()` virtual, then override its implementation for CUDA and OpenCL. Since I think copying the whole code base would be redundant, would you agree?
- Should I also add `SetPixel()` in `image_function_helper.h`?

**Comment by ihhub** [comment]
- no. OpenCL code is totally independent from CPU code. We have to write OpenCL kernel which will be called from newly created function
- Yes.

**Comment by josephnicholas** [comment]
@ihhub Thanks, things below that I don't quite understand.

- Program Kernel, for the 2 implementation of `SetPixel` I assume that I should make one kernel call for each function am I correct? how are the parameter mapped since I noticed it is not a 1:1 call with the function.

- For `image_function_helper` I noticed that basing on the `Subtract` implementation it has 3 returns `2 void and 1 Image`, should I also do the same thing with `SetPixel`? I noticed that this is something like a function pointer that creates a callable based on the parameters, but I noticed that when called in `image_function_opencl` it is functions from `image_function_helper` are called, and one for the actual implementation.

- One last thing is the `ParameterValidation` so the 2nd `SetPixel` has params that are not supported by the function, should I add a support for this?

Trying my best to learn this interesting project. 💯 

Thanks.

**Comment by josephnicholas** [comment]
@ihhub any updates on my questions above? Thanks. :)

**Comment by ihhub** [comment]
Hi @josephnicholas , sorry for late reply.
- yes, you have to create 2 OpenCL kernels: one which has kernel size as 1 and another one with an array (you could refer to [this pull request](https://github.com/ihhub/penguinV/pull/556/files) as a full answer for your question)
- SetPixel() doesn't need any extra functions to be created inside `image_function_helper` because we don't have any dependencies between these 2 functions. For `Subtract` case we originally have 4 functions but only 1 of them does real calculations while the rest of 3 call this function internally. Image_function_helper was created to cope with code duplication for different platforms but unfortunately, not all functions could be grouped/refactored (at current stage)
- could you please provide a sample code with `ParameterValidation` function call? I can point a direction where to search or if something is wrong :)

**Comment by ihhub** [comment]
Regarding adding SetPixel into image_function_helper I was thinking about adding function pointers. My bad. You don't need to add anything new into this file as functions pointers exist for SetPixel.

**Comment by josephnicholas** [comment]
@ihhub created my initial commit, with few questions on handling the Arrays in kernel SetPixel call.

After which the functions are done I can do the unit testing part. Sorry I'm a bit draggy on the implementation.

https://github.com/ihhub/penguinV/pull/558

**Comment by josephnicholas** [comment]
@ihhub before I amend the code, I just took the reference in CUDA implementation for `SetPixel` for the kernel call. This is the code.

```c
       __kernel void setPixelOpenCL( __global const uchar * data, uint offset, uint rowSize, uint width, uint height, volatile __global uint * pointX,
                                      volatile __global uint * pointY, uint pointSize, uint value)
        {
            const size_t id = get_global_id(0);

            if ( id < pointSize ) {
                const uint32_t x = pointX[id];
                const uint32_t y = pointY[id];
                if ( x < width && y < height ) {
                    data[offset + y * rowSize + x] = value;
                }
            }
        }
```

**Comment by josephnicholas** [comment]
@ihhub I created some unit tests on this, but I am stuck on the `verifyImage`
```cpp
        bool verifyImage( const PenguinV_Image::Image & image, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint8_t value )
        {
            multiCL::Type< uint32_t > differenceCount( 0u );

            const multiCL::OpenCLProgram & program = GetProgram();
            multiCL::OpenCLKernel kernel( program, "isEqualOpenCL" );

            const uint32_t rowSize = image.rowSize();
            width *= image.colorCount();
            const uint32_t offset = x * rowSize + y;

            kernel.setArgument( image.data(), offset, value, rowSize, width, height, differenceCount.data() );

            multiCL::launchKernel2D( kernel, width, height );

            return ( differenceCount.get() == width * height );
        }
```

The function doesn't return anything, when I tried to debug it, and place `differenceCount.get()` into another variable it doesn't seem to return anything. That's why my test failed.

**Comment by ihhub** [comment]
@josephnicholas `differenceCount` is a variable allocated on GPU memory, you cannot directly copy it. `differenceCount.get()` is exactly what you need. This call converts GPU memory into CPU memory so you could check the value.

**Comment by josephnicholas** [comment]
@ihhub in which part of the `SetPixel()` implementation are you referring to sir?
