### ISSUE TITLE
Rename PenguinV_Image namespace into penguinV

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#543]
We would like to rename **PenguinV_Image** namespace which locates in `src/image_buffer.h`, `src/opencl/image_buffer_opencl.h` and `src/cuda/image_buffer_cuda.cuh` files into **penguinV**.

Please take note that in `src/penguinv/penguinv.h` file we have to remove `using namespace PenguinV_Image;` line after renaming.

**Comment by RahulRavishankar** [comment]
I'll work on it!

**Comment by ihhub** [comment]
Sure!
