### ISSUE TITLE
Add an extra verifyImage() function to OpenCL unit test helper

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#544]
Currently we have overloaded verifyImage() function for OpenCL unit test helper which locates in `test/unit_tests/opencl/unit_test_helper_opencl.h` and `test/unit_tests/opencl/unit_test_helper_opencl.cpp` files:

```cpp
bool verifyImage( const PenguinV_Image::Image & image, uint8_t value );
bool verifyImage( const PenguinV_Image::Image & image, const std::vector < uint8_t > & value );
```

We need to add 2 more overloaded instances of the same function as:
```cpp
bool verifyImage( const PenguinV_Image::Image & image, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint8_t value );
bool verifyImage( const PenguinV_Image::Image & image, uint32_t x, uint32_t y, uint32_t width, uint32_t height, const std::vector < uint8_t > & value );
```

These functions support ROI (region of interest) which is required for many functions.
Things to be done:
1. Add a definition of these functions in `test/unit_tests/opencl/unit_test_helper_opencl.h` file
2. Modify `isEqualOpenCL` and `isAnyEqualOpenCL` functions to include **offset** parameter. Please use `__kernel void fillOpenCL` in `src/opencl/image_function_opencl.cpp` file as a reference for this.
3. Move existing code from 2 existing `verifyImage` functions into new functions and calculate offset as an extra parameter for OpenCL kernel. Use `void Fill( Image & image, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint8_t value )` function in `src/opencl/image_function_opencl.cpp` file as a reference for this.
4. Call new `verifyImage` function from old function by adding 0 for **x** and **y** parameter and **image.width()** and **image.height()** as **width** and **height** parameters respectively.

**Comment by josephnicholas** [comment]
@ihhub task started.

**Comment by josephnicholas** [comment]
@ihhub would it rather be better to change the `uint32_t` to `auto`?

**Comment by ihhub** [comment]
In our project we prefer to avoid **auto** word. Plus we know that size dimensions are within uint32_t range.

**Comment by josephnicholas** [comment]
Pull request: https://github.com/ihhub/penguinV/pull/553

Thanks.
