### ISSUE TITLE
Move existing duplicated code from GammaCorrection() into on function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#545]
We have CPU, OpenCL and CUDA implementation of **GammaCorrection**() function. These functions contain exactly the same code:
```cpp
        if ( a < 0 || gamma < 0 )
            throw imageException( "Gamma correction parameters are invalid" );

        // We precalculate all values and store them in lookup table
        std::vector < uint8_t > value( 256, 255u );

        for ( uint16_t i = 0; i < 256; ++i ) {
            double data = a * pow( i / 255.0, gamma ) * 255 + 0.5;

            if ( data < 256 )
                value[i] = static_cast<uint8_t>(data);
        }
```

We would like to remove duplication code and create a new function called `std::vector<uint8_t> GetGammaCorrectionLookupTable( double a, double gamma )`. This function should be stored in `src/image_function_helper.h` and `src/image_function_helper.cpp` files. Call this function to retrieve an array of values.

**Comment by gumeo** [comment]
See https://github.com/ihhub/penguinV/pull/555
