### ISSUE TITLE
Modify Histogram() function to support color images

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#548]
We have an implementation of **Histogram()** function in `src/image_function.cpp` (without and with mask, there are 2 implementations). This function supports only gray-scale images for now. We want to add a support of color images as well. The output histogram for RGB image for example would be as follow red0, green0, blue0, red1, green1, blue1... In other words output array follows the same color channel structure an input image.
Steps to be done:
1. Remove `VerifyGrayScaleImage( image );` line
2. Change `histogram.resize( 256u );` into `histogram.resize( 256u * colorCount );`
3. Differentiate gray-scale image case (1 color channel) and multiple color channel so loops would be very efficient for every situation.

**Comment by pierre87** [comment]
I would like to try this one :)

**Comment by ihhub** [comment]
@pierre87 sure!
