### ISSUE TITLE
Add Travis auto build

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#55]
Add **Travis CI** (https://travis-ci.org) auto build for whole project. Do not put all files in root directory because it makes file structure messy. Put all needed files into ```travis_auto_build``` directory which would locate in root of project.

The project is already activated on Travis CI and the build status indicator is added too.

**Comment by SuhanKoh** [comment]
Hi, can this project build with MSBuild?

**Comment by ihhub** [comment]
Hi, @SuhanKoh . This is OS independent project so you can build it with Microsoft Visual Studio as it is done for unit, performance tests and examples.

**Comment by binhonglee** [comment]
I'm not really following, do you already have an existing testing suite you use to test the project locally?

**Comment by ihhub** [comment]
Hi, @binhonglee , the library has it's own unit and performance testing suite which is under appropriate folders but there are open issues (#3, #26, #44) related to this which requires some improvements. You can have a look on them.
