### ISSUE TITLE
Add unit tests for IsBinary() function

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#552]
We have an implementation of IsBinary() function in `src/image_function.cpp` file. We have unit tests for functions in `test/unit_tests/unit_test_image_function.cpp` file. For unit test you can refer to `IsEqual` implementation. We need to generate gray-scale image with 1 or 2 intensity values so we need to use `intensityArray` function.
Registration of these unit tests should be inside `namespace image_function` (refer to `SET_FUNCTION_2_FORMS( IsEqual )` code line).

**Comment by josephnicholas** [comment]
@ihhub I would like to work on this.

**Comment by ihhub** [comment]
@josephnicholas sure!
