### ISSUE TITLE
Optimisation steps for AppVeyor

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#554]
This is discussion topic for **AppVeyor** potential optimisation. Story behind:
I noticed that AppVeyor spends more than **8 minutes** to install packages such as libjpeg, libpng, yasm and zlib. I'm thinking that our approach is incorrect that we compile all these libraries during job run. For example, we could do something similar as I did [here](https://github.com/ihhub/fheroes2/blob/master/script/windows/install_packages.bat). This is not an ideal solution but the idea is that we download already compiled packages instead of recompiling them every time.

@yannlabou what do you think?

**Comment by ihhub** [comment]
At least we could do something like this: check Microsoft Visual Studio version. If the version is between 12 and 14 then we download compiled package from [official page](https://www.libs4win.com/libzlib/) and just unzip it. In case of different VS version we proceed with current solution.
The same could be applied for libjpeg and libpng.

Additionally, if we cannot find a proper place for compiled libraries we could release them in this github releases page and download them accordingly.

**Comment by yannlabou** [comment]
> 
> 
> This is discussion topic for **AppVeyor** potential optimisation. Story behind:
> I noticed that AppVeyor spends more than **8 minutes** to install packages such as libjpeg, libpng, yasm and zlib. I'm thinking that our approach is incorrect that we compile all these libraries during job run. For example, we could do something similar as I did [here](https://github.com/ihhub/fheroes2/blob/master/script/windows/install_packages.bat). This is not an ideal solution but the idea is that we download already compiled packages instead of recompiling them every time.
> 
> @yannlabou what do you think?

I agree that building from sources takes time but it's what we decided at that time. Of course we could also directly install the binaries. As I will be on vacation the next weeks, I'll take care of this take in November if it's not urgent. Let's finish #549 first ;).

**Comment by ihhub** [comment]
After the changes we left with:
1. **zlib** installation - 25 seconds
2. **jpeg** installation - 3 minutes
3. **png** installation - 10 seconds
