### ISSUE TITLE
Static library compilation

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#56]
As a library the project should be built as a static library as well. We must add necessary project/make files for this.

From design point of view it's a good practice to put project/make files out of main ```PenguinV\Library``` directory. Recommended path for this is ```PenguinV\build\static_library```

**Comment by platipo** [comment]
Correct me if I'm wrong, you want the sources in Library folder to compile into a static library?

**Comment by ihhub** [comment]
Hi, @platipo ,

Yes, you are correct. Ideally all files and folders within ```Library``` folder (including CUDA code as well).

**Comment by platipo** [comment]
Got a problem:
```
g++ -Wall -g -O0 -pthread -std=c++11 -c penguinv/penguinv.cpp -o penguinv/penguinv.o
In file included from penguinv/penguinv.cpp:1:0:
penguinv/cpu_identification.h:42:3: error: #error "Unknown platform"
  #error "Unknown platform"
   ^~~~~
make: *** [Makefile:21: penguinv/penguinv.o] Error 1
```

**Comment by platipo** [comment]
And also:
```
image_function_neon.cpp:1:10: fatal error: arm_neon.h: No such file or directory
 #include <arm_neon.h>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:21: image_function_neon.o] Error 1
```
Even though `$ g++ -march=native -dM -E - </dev/null | grep -i arm` returns nothing.

**Comment by ihhub** [comment]
Library has not been tested for a while under Linux so your suggestion could be correct.

Neon is SIMD instruction set which is only for ARM processors. I assume you compile on x86 processor. But I will make a proper changes for this for avoid such problem.

**Comment by ihhub** [comment]
Closing this issue as we have similar issue.
