### ISSUE TITLE
Make Static Analisys job a bit more friendly.

### ISSUE THREAD

**Issue by fullset** [ihhub/penguinV#567]
In general, the job of Static Analysis in Travis only works on the new code. Sometimes it's very good, for example, when you add a new feature. But sometimes when you change existing code, like #543 the result could be a bit annoying (https://travis-ci.org/ihhub/penguinV/jobs/598507494). And this is not very obvious for contributors what to do in this case.

It could be a not very bad idea to do one of two possible things:
1) Change all the sources according to the Code Style.
2) Change the code style according to the existing source (if it's possible)

or maybe something else?

**Comment by ihhub** [comment]
@fullset I agree with you. I'm working on this issue... It's same problem for my another project :(

**Comment by ihhub** [comment]
It is fixed with full code reformatting to a single code style standard.
