### ISSUE TITLE
Remove Qt installation from normal builds on servers

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#573]
We have only a tiny piece of code which is written for Qt but we spend many minutes of our build time to install Qt framework on virtual machines. We not need to install Qt on virtual machines for normal builds on Travis-CI and AppVeyor but we will use Qt installation for schedules jobs which are going to run every day.

**Comment by ihhub** [comment]
My aim is to get build time for single commit on Travis-CI is below 10 minutes (now it's about 15 minutes) and below 20 minutes (now it's about 30 minutes).

**Comment by yannlabou** [comment]
Hi @ihhub. I'll look into it. I traveled a lot the last 5 weeks :).

**Comment by ihhub** [comment]
Hi @yannlabou , welcome back!

Let's focus only on **Travis-CI** for now as I haven't got approval from AppVeyor team to enable scheduled builds for the project.

**Comment by yannlabou** [comment]
@ihhub What do you think about wrapping the whole build environment in an `Docker` image so that `Travis` only need to run the Docker image? It's a little bit of initial work but it will reduce the whole build execution time as the install/update steps won't be necessary anymore.

**Comment by ihhub** [comment]
I'm totally okay with Docker as I work with it as well. Let's try this way if we can build the project with Docker containers.

**Comment by ihhub** [comment]
I think we could add Qt and CUDA containers to even more save time for builds.

**Comment by yannlabou** [comment]
Our Travis default environment is still Ubuntu Xenial with g++ 5.4.0. Do we keep it as it is or upgrade to Ubuntu Bionic with g++ 7.3.0?

**Comment by 0x72D0** [comment]
@ihhub I think we should upgrade since -march=skylake-avx512 is supported on gcc 6 or later: https://gcc.gnu.org/gcc-6/changes.html

**Comment by ihhub** [comment]
Closing this issue as it was addressed in our builds, especially for AppVeyor.
