### ISSUE TITLE
Add unit tests for ProjectionProfile functions implemented in CUDA

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#579]
We have an implemented of **ProjectionProfile** for CUDA which locates in `src/cuda/image_function_cuda.cuh` and `src/cuda/image_function_cuda.cu` files. We have unit tests for CUDA functions which locate in `penguinV/test/unit_tests/cuda/unit_test_image_function_cuda.cpp` file. We need to add unit tests for mentioned above function.

**Comment by ihhub** [comment]
Hi @josephnicholas you could work on this task which is directly related to your previous PR. Unit tests are needed to prove that code is correct.

**Comment by josephnicholas** [comment]
@ihhub thanks for the opportunity I will work on this.

**Comment by josephnicholas** [comment]
Stuck on error `[1/9] image_function_cuda::ProjectionProfileForm1Test... ERROR : library exception 'Cannot copy a memory in CUDA device' raised` when calling `ProjectionProfile`. @ihhub can you shed some light on this error?
