### ISSUE TITLE
Rework library structure

### ISSUE THREAD

**Issue by platipo** [ihhub/penguinV#59]
As stated in #57 project structure should adapt to standard project structure. It is also necessary to create headers that expose API
[Reference](https://stackoverflow.com/questions/1398445/directory-structure-for-a-c-library#1398594)

EDIT: `include`

**Comment by ihhub** [comment]
This issue is correlated to #47

**Comment by ihhub** [comment]
This issue is under discussion because the project is **not** for Unix only systems.

**Comment by platipo** [comment]
[Here a **non-Unix** link](https://www.quora.com/What-is-a-general-C++-project-structure-like) explained in far more detail.

**Comment by yannlabou** [comment]
I had suggest following this [library layout](https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/pitchfork/develop/data/spec.bs).
