### ISSUE TITLE
Modify examples/image_function example to use functions from penguinV namespace

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#601]
Modify examples/image_function example to use functions from penguinV namespace which are located in `src/penguinv/penguinv.h` and `src/penguinv/penguinv.cpp` files. Simple as it is. Don't forget to include these files into project file settings within the example.

**Comment by manekenpix** [comment]
Can I work on this one?

**Comment by ihhub** [comment]
Hi @manekenpix , sure!
