### ISSUE TITLE
Use AVX512 simulation header to check code

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#611]
We'd like to check AVX512 code. Right now we don't have any hardware to do such but we could simulated AVX512 via Intel simulation header file.
The name of the file should be `avxintrin_emu.h`. A good start is to read [this article](https://software.intel.com/en-us/articles/intel-software-development-emulator).

**Comment by ihhub** [comment]
Hi @0x72D0 would you like to validate your AVX-512 code by this approach?

**Comment by 0x72D0** [comment]
@ihhub yeah sure, but I'm sure I follow you when you talk about a header for the emulation. The article you link only talk about a standalone software for the emulation.

**Comment by ihhub** [comment]
Hi @0x72D0 I'm talking about this header - `avxintrin_emu` There should be some sort of simulation provided by Intel as AVX-512 is Intel technology.

**Comment by ihhub** [comment]
Closing this issue as we have real hardware with AVX-512 support.
