### ISSUE TITLE
load image from memory?

### ISSUE THREAD

**Issue by Ryder17z** [ihhub/penguinV#692]
I would like to load an image from memory.

My sources may be base64 encoded so it would be nice to just decode them if necessary and load the contents directly, eliminating the need for a temporary file acting as a buffer.

Is there a way to do this?

**Comment by ihhub** [comment]
Hi @Ryder17z , since you know the base64 buffer length and possibly width and height, you can just allocate needed size image and get its buffer. Then write / call a function to do decoding of your buffer.

**Comment by ihhub** [comment]
Closing this issue as answered.
