### ISSUE TITLE
Add QT support for Travis CI

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#72]
Travis CI potentially supports QT framework and we already have an example code with QT. Why don't we do it?

https://forum.qt.io/topic/50340/installing-qt-5-4-dev-packages-in-travis-ci
http://osdevlab.blogspot.com/2016/02/simple-unit-test-with-qt-continuous.html

**Comment by yannlabou** [comment]
What Qt5 version do we want to support here?

**Comment by ihhub** [comment]
Ah, sorry. Missed you previous question. There is no any preference in QT but I recommend 5.6 or 5.9.

Yes, you could work on it
