### ISSUE TITLE
Processing acceleration of full row ROI

### ISSUE THREAD

**Issue by ihhub** [ihhub/penguinV#87]
If we process an image with ROI of full row (`ROW.width = image.width`) and the image has 1 byte alignment for each row we can accelerate calculations by simply set width as `width * height` and height as `1` giving an advantage to SIMD instructions as well.

**Comment by 0x72D0** [comment]
I will try this one next :)

**Comment by 0x72D0** [comment]
In which file I should implement this?

**Comment by ihhub** [comment]
Sure. We need to modify `src/image_function_simd.cpp` file in `namespace simd` we just make such trick as set height to 1 while with would be `width * height`. So the code should be something like this:
```cpp
if( (width == imageIn.rowSize()) && (width == imageOut.rowSize()) {
    width = width * height;
    height = 1;
}
```

But we must be sure that there would be no variable overflow.

**Comment by 0x72D0** [comment]
ok

**Comment by ihhub** [comment]
I recommend to make such code as a separate function to save time and space. This function would be located in `namespace simd` just before line `using namespace PenguinV_Image;`.
Let's call it something like **OptimiseROI**. I think we should have a variadic template function (you can get a look into such function into `src/parameter_validation.h` file).

`width` and `height` must be references.

**Comment by ihhub** [comment]
I think you could avoid variable overflow check as people very rarely work with images bigger than 4 GB :)

**Comment by 0x72D0** [comment]
can we use C++17 feature in this project?

**Comment by ihhub** [comment]
Which C++17 feature do you want to use?

**Comment by 0x72D0** [comment]
expression folding

**Comment by ihhub** [comment]
I don't see any advantage to use such feature. C++11 already supports variadic templates which is totally fine for us. If I'm wrong could you please explain what advantage will we have using expression folder?

**Comment by ihhub** [comment]
From my personal experience it's better not to use latest C++ features as it kills a potential range of users who don't use latest version (backward compatibility) and sometimes we can implement the same feature (if it's not big) in older C++ versions :)

**Comment by 0x72D0** [comment]
oh I just wanted to do something like this:

```
template <typename Type, typename TImage, typename... Args>
    bool widthCondition(const Type & width, TImage image, Args... args)
    {
        if( (image.rowSize() == width) && ... )
        {
            return true;
        }
        return false;
    }

    template <typename Type>
    void OptimiseROI( Type & height, Type & width )
    {
        // variable overflow check
        if(width < std::numeric_limits<uint32_t>::max()/height)
        {
            width = width * height;
            height = 1;
        }
    }

    template <typename Type, typename TImage, typename... Args>
    void OptimiseROI(Type & height, Type & width, TImage image, Args... args)
    {
        if(widthCondition(width, image, args...))
            OptimiseROI( height, width );
    }
```

but I'm gonna try to see another way to evaluate if all the images rowsize are equal to the width :)
